  CV_8U =  0;
  CV_8S =  1;
  CV_16U =  2;
  CV_16S =  3;
  CV_32S =  4;
  CV_32F =  5;
  CV_64F =  6;
  CV_16F =  7;
  CV_8UC1 =  0;
  CV_8UC2 =  8;
  CV_8UC3 =  16;
  CV_8UC4 =  24;
  CV_8SC1 =  1;
  CV_8SC2 =  9;
  CV_8SC3 =  17;
  CV_8SC4 =  25;
  CV_16UC1 =  2;
  CV_16UC2 =  10;
  CV_16UC3 =  18;
  CV_16UC4 =  26;
  CV_16SC1 =  3;
  CV_16SC2 =  11;
  CV_16SC3 =  19;
  CV_16SC4 =  27;
  CV_32SC1 =  4;
  CV_32SC2 =  12;
  CV_32SC3 =  20;
  CV_32SC4 =  28;
  CV_32FC1 =  5;
  CV_32FC2 =  13;
  CV_32FC3 =  21;
  CV_32FC4 =  29;
  CV_64FC1 =  6;
  CV_64FC2 =  14;
  CV_64FC3 =  22;
  CV_64FC4 =  30;
  CV_USRTYPE1 =  7;
  FILLED =  -1;
  LINE_AA =  16;
  LINE_8 =  8;
  LINE_4 =  4;
  REDUCE_SUM =  0;
  REDUCE_AVG =  1;
  REDUCE_MAX =  2;
  REDUCE_MIN =  3;
  KIND_SHIFT =  16;
  CV_AA =  16;
  CV_MOP_ERODE =  0;
  CV_MOP_DILATE =  1;
  CV_MOP_OPEN =  2;
  CV_MOP_CLOSE =  3;
  CV_MOP_GRADIENT =  49;
  CV_MOP_TOPHAT =  5;
  CV_MOP_BLACKHAT =  6;
  CV_MAT_CONT_FLAG =  16384;
  CV_SUBMAT_FLAG =  32768;
  CV_MAX_DIM =  32;
  CV_INTER_NN =  0;
  CV_INTER_LINEAR =  1;
  CV_INTER_CUBIC =  2;
  CV_INTER_AREA =  3;
  CV_INTER_LANCZOS4 =  4;
  CV_WARP_INVERSE_MAP =  16;
  CV_THRESH_BINARY =  0;
  CV_THRESH_BINARY_INV =  1;
  CV_THRESH_TRUNC =  2;
  CV_THRESH_TOZERO =  3;
  CV_THRESH_TOZERO_INV =  4;
  CV_THRESH_MASK =  7;
  CV_THRESH_OTSU =  8;
  CV_RETR_EXTERNAL =  0;
  CV_RETR_LIST =  1;
  CV_RETR_CCOMP =  2;
  CV_RETR_TREE =  3;
  CV_RETR_FLOODFILL =  4;
  CV_CHAIN_APPROX_NONE =  1;
  CV_CHAIN_APPROX_SIMPLE =  2;
  CV_CHAIN_APPROX_TC89_L1 =  3;
  CV_CHAIN_APPROX_TC89_KCOS =  4;
  CV_WND_PROP_FULLSCREEN =  0;
  CV_WND_PROP_AUTOSIZE =  1;
  CV_WND_PROP_ASPECTRATIO =  2;
  CV_WND_PROP_OPENGL =  3;
  CV_WINDOW_NORMAL =  0;
  CV_WINDOW_AUTOSIZE =  1;
  CV_WINDOW_OPENGL =  4096;
  CV_INPAINT_NS =  0;
  CV_INPAINT_TELEA =  1;
  IPL_BORDER_CONSTANT =  0;
  IPL_BORDER_REPLICATE =  1;
  IPL_BORDER_REFLECT =  2;
  IPL_BORDER_WRAP =  3;
  IPL_BORDER_REFLECT_101 =  4;
  IPL_BORDER_TRANSPARENT =  5;
  CV_LMEDS =  4;
  CV_RANSAC =  8;
  CV_FM_LMEDS =  CV_LMEDS;
  CV_FM_RANSAC =  CV_RANSAC;
  CV_FM_7POINT =  1;
  CV_FM_8POINT =  2;
  CV_CALIB_USE_INTRINSIC_GUESS =  1;
  CV_CALIB_FIX_ASPECT_RATIO =  2;
  CV_CALIB_FIX_PRINCIPAL_POINT =  4;
  CV_CALIB_ZERO_TANGENT_DIST =  8;
  CV_CALIB_FIX_FOCAL_LENGTH =  16;
  CV_CALIB_FIX_K1 =  32;
  CV_CALIB_FIX_K2 =  64;
  CV_CALIB_FIX_K3 =  128;
  CV_CALIB_FIX_K4 =  2048;
  CV_CALIB_FIX_K5 =  4096;
  CV_CALIB_FIX_K6 =  8192;
  CV_CALIB_RATIONAL_MODEL =  16384;
  CV_CALIB_FIX_INTRINSIC =  256;
  CV_CALIB_SAME_FOCAL_LENGTH =  512;
  CV_CALIB_ZERO_DISPARITY =  1024;
  CV_LKFLOW_INITIAL_GUESSES =  4;
  CV_LKFLOW_GET_MIN_EIGENVALS =  8;
  CV_HAAR_DO_CANNY_PRUNING =  1;
  CV_HAAR_SCALE_IMAGE =  2;
  CV_HAAR_FIND_BIGGEST_OBJECT =  4;
  CV_HAAR_DO_ROUGH_SEARCH =  8;
  LMEDS =  4;
  RANSAC =  8;
  RHO =  16;
  USAC_DEFAULT =  32;
  USAC_PARALLEL =  33;
  USAC_FM_8PTS =  34;
  USAC_FAST =  35;
  USAC_ACCURATE =  36;
  USAC_PROSAC =  37;
  USAC_MAGSAC =  38;
Type
  TCvSolvePnPMethod = (  SOLVEPNP_ITERATIVE =  0,  SOLVEPNP_EPNP =  1,  SOLVEPNP_P3P =  2,
          SOLVEPNP_DLS =  3,  SOLVEPNP_UPNP =  4,  SOLVEPNP_AP3P =  5,
          SOLVEPNP_IPPE =  6,  SOLVEPNP_IPPE_SQUARE =  7,  SOLVEPNP_SQPNP =  8,
          SOLVEPNP_MAX_COUNT =  8+1  );
Const
  CALIB_CB_ADAPTIVE_THRESH =  1;
  CALIB_CB_NORMALIZE_IMAGE =  2;
  CALIB_CB_FILTER_QUADS =  4;
  CALIB_CB_FAST_CHECK =  8;
  CALIB_CB_EXHAUSTIVE =  16;
  CALIB_CB_ACCURACY =  32;
  CALIB_CB_LARGER =  64;
  CALIB_CB_MARKER =  128;
  CALIB_CB_SYMMETRIC_GRID =  1;
  CALIB_CB_ASYMMETRIC_GRID =  2;
  CALIB_CB_CLUSTERING =  4;
  CALIB_NINTRINSIC =  18;
  CALIB_USE_INTRINSIC_GUESS =  $00001;
  CALIB_FIX_ASPECT_RATIO =  $00002;
  CALIB_FIX_PRINCIPAL_POINT =  $00004;
  CALIB_ZERO_TANGENT_DIST =  $00008;
  CALIB_FIX_FOCAL_LENGTH =  $00010;
  CALIB_FIX_K1 =  $00020;
  CALIB_FIX_K2 =  $00040;
  CALIB_FIX_K3 =  $00080;
  CALIB_FIX_K4 =  $00800;
  CALIB_FIX_K5 =  $01000;
  CALIB_FIX_K6 =  $02000;
  CALIB_RATIONAL_MODEL =  $04000;
  CALIB_THIN_PRISM_MODEL =  $08000;
  CALIB_FIX_S1_S2_S3_S4 =  $10000;
  CALIB_TILTED_MODEL =  $40000;
  CALIB_FIX_TAUX_TAUY =  $80000;
  CALIB_USE_QR =  $100000;
  CALIB_FIX_TANGENT_DIST =  $200000;
  CALIB_FIX_INTRINSIC =  $00100;
  CALIB_SAME_FOCAL_LENGTH =  $00200;
  CALIB_ZERO_DISPARITY =  $00400;
  CALIB_USE_LU =  (1  shl  17);
  CALIB_USE_EXTRINSIC_GUESS =  (1  shl  22);
  FM_7POINT =  1;
  FM_8POINT =  2;
  FM_LMEDS =  4;
  FM_RANSAC =  8;
Type
  TCvHandEyeCalibrationMethod = (  CALIB_HAND_EYE_TSAI =  0,  CALIB_HAND_EYE_PARK =  1,  CALIB_HAND_EYE_HORAUD =  2,
          CALIB_HAND_EYE_ANDREFF =  3,  CALIB_HAND_EYE_DANIILIDIS =  4  );
  TCvRobotWorldHandEyeCalibrationMethod = (  CALIB_ROBOT_WORLD_HAND_EYE_SHAH =  0,  CALIB_ROBOT_WORLD_HAND_EYE_LI =  1  );
  TCvSamplingMethod = (  SAMPLING_UNIFORM =  0,  SAMPLING_PROGRESSIVE_NAPSAC =  1,  SAMPLING_NAPSAC =  2,
          SAMPLING_PROSAC =  3  );
  TCvLocalOptimMethod = (  LOCAL_OPTIM_NULL =  0,  LOCAL_OPTIM_INNER_LO =  1,  LOCAL_OPTIM_INNER_AND_ITER_LO =  2,
          LOCAL_OPTIM_GC =  3,  LOCAL_OPTIM_SIGMA =  4  );
  TCvScoreMethod = (  SCORE_METHOD_RANSAC =  0,  SCORE_METHOD_MSAC =  1,  SCORE_METHOD_MAGSAC =  2,
          SCORE_METHOD_LMEDS =  3  );
  TCvNeighborSearchMethod = (  NEIGH_FLANN_KNN =  0,  NEIGH_GRID =  1,  NEIGH_FLANN_RADIUS =  2  );
  TCvCirclesGridFinderParameters_GridType = (  SYMMETRIC_GRID =  0,  ASYMMETRIC_GRID =  1  );
Const
  STEREOMATCHER_DISP_SHIFT =  4;
  STEREOMATCHER_DISP_SCALE =  (1  shl  STEREOMATCHER_DISP_SHIFT);
  STEREOBM_PREFILTER_NORMALIZED_RESPONSE =  0;
  STEREOBM_PREFILTER_XSOBEL =  1;
  STEREOSGBM_MODE_SGBM =  0;
  STEREOSGBM_MODE_HH =  1;
  STEREOSGBM_MODE_SGBM_3WAY =  2;
  STEREOSGBM_MODE_HH4 =  3;
Type
  TCvUndistortTypes = (  PROJ_SPHERICAL_ORTHO =  0,  PROJ_SPHERICAL_EQRECT =  1  );
Const
  FISHEYE_CALIB_USE_INTRINSIC_GUESS =  1  shl  0;
  FISHEYE_CALIB_RECOMPUTE_EXTRINSIC =  1  shl  1;
  FISHEYE_CALIB_CHECK_COND =  1  shl  2;
  FISHEYE_CALIB_FIX_SKEW =  1  shl  3;
  FISHEYE_CALIB_FIX_K1 =  1  shl  4;
  FISHEYE_CALIB_FIX_K2 =  1  shl  5;
  FISHEYE_CALIB_FIX_K3 =  1  shl  6;
  FISHEYE_CALIB_FIX_K4 =  1  shl  7;
  FISHEYE_CALIB_FIX_INTRINSIC =  1  shl  8;
  FISHEYE_CALIB_FIX_PRINCIPAL_POINT =  1  shl  9;
  FISHEYE_CALIB_ZERO_DISPARITY =  1  shl  10;
  FISHEYE_CALIB_FIX_FOCAL_LENGTH =  1  shl  11;
Type
  TCvSortFlags = (  SORT_EVERY_ROW =  0,  SORT_EVERY_COLUMN =  1,  SORT_ASCENDING =  0,
          SORT_DESCENDING =  16  );
  TCvCovarFlags = (  COVAR_SCRAMBLED =  0,  COVAR_NORMAL =  1,  COVAR_USE_AVG =  2,
          COVAR_SCALE =  4,  COVAR_ROWS =  8,  COVAR_COLS =  16  );
  TCvKmeansFlags = (  KMEANS_RANDOM_CENTERS =  0,  KMEANS_PP_CENTERS =  2,  KMEANS_USE_INITIAL_LABELS =  1  );
  TCvRotateFlags = (  ROTATE_90_CLOCKWISE =  0,  ROTATE_180 =  1,  ROTATE_90_COUNTERCLOCKWISE =  2  );
  TCvPCA_Flags = (  DATA_AS_ROW =  0,  DATA_AS_COL =  1,  USE_AVG =  2  );
  TCvSVD_Flags = (  MODIFY_A =  1,  NO_UV =  2,  FULL_UV =  4  );
Const
  RNG_UNIFORM =  0;
  RNG_NORMAL =  1;
Type
  TCvFormatter_FormatType = (  FMT_DEFAULT =  0,  FMT_MATLAB =  1,  FMT_CSV =  2,
          FMT_PYTHON =  3,  FMT_NUMPY =  4,  FMT_C =  5  );
  TCvParam = (  _INT =  0,  _BOOLEAN =  1,  _REAL =  2,
          _STRING =  3,  _MAT =  4,  _MAT_VECTOR =  5,
          _ALGORITHM =  6,  _FLOAT =  7,  _UNSIGNED_INT =  8,
          _UINT64 =  9,  _UCHAR =  11,  _SCALAR =  12  );
  TCvError_Code = (  STSOK =  0,  STSBACKTRACE =  -1,  STSERROR =  -2,
          STSINTERNAL =  -3,  STSNOMEM =  -4,  STSBADARG =  -5,
          STSBADFUNC =  -6,  STSNOCONV =  -7,  STSAUTOTRACE =  -8,
          HEADERISNULL =  -9,  BADIMAGESIZE =  -10,  BADOFFSET =  -11,
          BADDATAPTR =  -12,  BADSTEP =  -13,  BADMODELORCHSEQ =  -14,
          BADNUMCHANNELS =  -15,  BADNUMCHANNEL1U =  -16,  BADDEPTH =  -17,
          BADALPHACHANNEL =  -18,  BADORDER =  -19,  BADORIGIN =  -20,
          BADALIGN =  -21,  BADCALLBACK =  -22,  BADTILESIZE =  -23,
          BADCOI =  -24,  BADROISIZE =  -25,  MASKISTILED =  -26,
          STSNULLPTR =  -27,  STSVECLENGTHERR =  -28,  STSFILTERSTRUCTCONTENTERR =  -29,
          STSKERNELSTRUCTCONTENTERR =  -30,  STSFILTEROFFSETERR =  -31,  STSBADSIZE =  -201,
          STSDIVBYZERO =  -202,  STSINPLACENOTSUPPORTED =  -203,  STSOBJECTNOTFOUND =  -204,
          STSUNMATCHEDFORMATS =  -205,  STSBADFLAG =  -206,  STSBADPOINT =  -207,
          STSBADMASK =  -208,  STSUNMATCHEDSIZES =  -209,  STSUNSUPPORTEDFORMAT =  -210,
          STSOUTOFRANGE =  -211,  STSPARSEERROR =  -212,  STSNOTIMPLEMENTED =  -213,
          STSBADMEMBLOCK =  -214,  STSASSERT =  -215,  GPUNOTSUPPORTED =  -216,
          GPUAPICALLERROR =  -217,  OPENGLNOTSUPPORTED =  -218,  OPENGLAPICALLERROR =  -219,
          OPENCLAPICALLERROR =  -220,  OPENCLDOUBLENOTSUPPORTED =  -221,  OPENCLINITERROR =  -222,
          OPENCLNOAMDBLASFFT =  -223  );
  TCvDecompTypes = (  DECOMP_LU =  0,  DECOMP_SVD =  1,  DECOMP_EIG =  2,
          DECOMP_CHOLESKY =  3,  DECOMP_QR =  4,  DECOMP_NORMAL =  16  );
  TCvNormTypes = (  NORM_INF =  1,  NORM_L1 =  2,  NORM_L2 =  4,
          NORM_L2SQR =  5,  NORM_HAMMING =  6,  NORM_HAMMING2 =  7,
          NORM_TYPE_MASK =  7,  NORM_RELATIVE =  8,  NORM_MINMAX =  32  );
  TCvCmpTypes = (  CMP_EQ =  0,  CMP_GT =  1,  CMP_GE =  2,
          CMP_LT =  3,  CMP_LE =  4,  CMP_NE =  5  );
  TCvGemmFlags = (  GEMM_1_T =  1,  GEMM_2_T =  2,  GEMM_3_T =  4  );
  TCvDftFlags = (  DFT_INVERSE =  1,  DFT_SCALE =  2,  DFT_ROWS =  4,
          DFT_COMPLEX_OUTPUT =  16,  DFT_REAL_OUTPUT =  32,  DFT_COMPLEX_INPUT =  64,
          DCT_INVERSE =  DFT_INVERSE,  DCT_ROWS =  DFT_ROWS  );
  TCvBorderTypes = (  BORDER_CONSTANT =  0,  BORDER_REPLICATE =  1,  BORDER_REFLECT =  2,
          BORDER_WRAP =  3,  BORDER_REFLECT_101 =  4,  BORDER_TRANSPARENT =  5,
          BORDER_REFLECT101 =  BORDER_REFLECT_101,  BORDER_DEFAULT =  BORDER_REFLECT_101,  BORDER_ISOLATED =  16  );
  TCvAccessFlag = (  ACCESS_READ =  1 shl 24,  ACCESS_WRITE =  1 shl 25,  ACCESS_RW =  3 shl 24,
          ACCESS_MASK =  ACCESS_RW,  ACCESS_FAST =  1 shl 26  );
  TCv_InputArray_KindFlag = (  INPUTARRAY_KIND_SHIFT =  16,  INPUTARRAY_FIXED_TYPE =  $8000  shl  KIND_SHIFT,  INPUTARRAY_FIXED_SIZE =  $4000  shl  KIND_SHIFT,
          INPUTARRAY_KIND_MASK =  31  shl  KIND_SHIFT,  INPUTARRAY_NONE =  0  shl  KIND_SHIFT,  INPUTARRAY_MAT =  1  shl  KIND_SHIFT,
          INPUTARRAY_MATX =  2  shl  KIND_SHIFT,  INPUTARRAY_STD_VECTOR =  3  shl  KIND_SHIFT,  INPUTARRAY_STD_VECTOR_VECTOR =  4  shl  KIND_SHIFT,
          INPUTARRAY_STD_VECTOR_MAT =  5  shl  KIND_SHIFT,  INPUTARRAY_EXPR =  6  shl  KIND_SHIFT,  INPUTARRAY_OPENGL_BUFFER =  7  shl  KIND_SHIFT,
          INPUTARRAY_CUDA_HOST_MEM =  8  shl  KIND_SHIFT,  INPUTARRAY_CUDA_GPU_MAT =  9  shl  KIND_SHIFT,  INPUTARRAY_UMAT =  10  shl  KIND_SHIFT,
          INPUTARRAY_STD_VECTOR_UMAT =  11  shl  KIND_SHIFT,  INPUTARRAY_STD_BOOL_VECTOR =  12  shl  KIND_SHIFT,  INPUTARRAY_STD_VECTOR_CUDA_GPU_MAT =  13  shl  KIND_SHIFT,
          INPUTARRAY_STD_ARRAY =  14  shl  KIND_SHIFT,  INPUTARRAY_STD_ARRAY_MAT =  15  shl  KIND_SHIFT  );
  TCv_OutputArray_DepthMask = (  OUTPUTARRAY_DEPTH_MASK_8U =  1  shl  CV_8U,  OUTPUTARRAY_DEPTH_MASK_8S =  1  shl  CV_8S,  OUTPUTARRAY_DEPTH_MASK_16U =  1  shl  CV_16U,
          OUTPUTARRAY_DEPTH_MASK_16S =  1  shl  CV_16S,  OUTPUTARRAY_DEPTH_MASK_32S =  1  shl  CV_32S,  OUTPUTARRAY_DEPTH_MASK_32F =  1  shl  CV_32F,
          OUTPUTARRAY_DEPTH_MASK_64F =  1  shl  CV_64F,  OUTPUTARRAY_DEPTH_MASK_16F =  1  shl  CV_16F,  OUTPUTARRAY_DEPTH_MASK_ALL =  (ord(OUTPUTARRAY_DEPTH_MASK_64F) shl 1)-1,
          OUTPUTARRAY_DEPTH_MASK_ALL_BUT_8S =  OUTPUTARRAY_DEPTH_MASK_ALL  and not ord(OUTPUTARRAY_DEPTH_MASK_8S),  OUTPUTARRAY_DEPTH_MASK_ALL_16F =  (ord(OUTPUTARRAY_DEPTH_MASK_16F) shl 1)-1,  OUTPUTARRAY_DEPTH_MASK_FLT =  OUTPUTARRAY_DEPTH_MASK_32F + OUTPUTARRAY_DEPTH_MASK_64F  );
  TCvUMatUsageFlags = (  USAGE_DEFAULT =  0,  USAGE_ALLOCATE_HOST_MEMORY =  1  shl  0,  USAGE_ALLOCATE_DEVICE_MEMORY =  1  shl  1,
          USAGE_ALLOCATE_SHARED_MEMORY =  1  shl  2,  __UMAT_USAGE_FLAGS_32BIT =  $7fffffff  );
  TCvUMatData_MemoryFlag = (  COPY_ON_MAP =  1,  HOST_COPY_OBSOLETE =  2,  DEVICE_COPY_OBSOLETE =  4,
          TEMP_UMAT =  8,  TEMP_COPIED_UMAT =  24,  USER_ALLOCATED =  32,
          DEVICE_MEM_MAPPED =  64,  ASYNC_CLEANUP =  128  );
Const
  MAT_MAGIC_VAL =  $42FF0000;
  MAT_AUTO_STEP =  0;
  MAT_CONTINUOUS_FLAG =  CV_MAT_CONT_FLAG;
  MAT_SUBMATRIX_FLAG =  CV_SUBMAT_FLAG;
  MAT_MAGIC_MASK =  $FFFF0000;
  MAT_TYPE_MASK =  $00000FFF;
  MAT_DEPTH_MASK =  7;
  UMAT_MAGIC_VAL =  $42FF0000;
  UMAT_AUTO_STEP =  0;
  UMAT_CONTINUOUS_FLAG =  CV_MAT_CONT_FLAG;
  UMAT_SUBMATRIX_FLAG =  CV_SUBMAT_FLAG;
  UMAT_MAGIC_MASK =  $FFFF0000;
  UMAT_TYPE_MASK =  $00000FFF;
  UMAT_DEPTH_MASK =  7;
  SPARSEMAT_MAGIC_VAL =  $42FD0000;
  SPARSEMAT_MAX_DIM =  32;
  SPARSEMAT_HASH_SCALE =  $5bd1e995;
  SPARSEMAT_HASH_BIT =  $80000000;
  OCL_DEVICE_TYPE_DEFAULT =  (1  shl  0);
  OCL_DEVICE_TYPE_CPU =  (1  shl  1);
  OCL_DEVICE_TYPE_GPU =  (1  shl  2);
  OCL_DEVICE_TYPE_ACCELERATOR =  (1  shl  3);
  OCL_DEVICE_TYPE_DGPU =  OCL_DEVICE_TYPE_GPU + (1  shl  16);
  OCL_DEVICE_TYPE_IGPU =  OCL_DEVICE_TYPE_GPU + (1  shl  17);
  OCL_DEVICE_TYPE_ALL =  $FFFFFFFF;
  OCL_DEVICE_FP_DENORM =  (1  shl  0);
  OCL_DEVICE_FP_INF_NAN =  (1  shl  1);
  OCL_DEVICE_FP_ROUND_TO_NEAREST =  (1  shl  2);
  OCL_DEVICE_FP_ROUND_TO_ZERO =  (1  shl  3);
  OCL_DEVICE_FP_ROUND_TO_INF =  (1  shl  4);
  OCL_DEVICE_FP_FMA =  (1  shl  5);
  OCL_DEVICE_FP_SOFT_FLOAT =  (1  shl  6);
  OCL_DEVICE_FP_CORRECTLY_ROUNDED_DIVIDE_SQRT =  (1  shl  7);
  OCL_DEVICE_EXEC_KERNEL =  (1  shl  0);
  OCL_DEVICE_EXEC_NATIVE_KERNEL =  (1  shl  1);
  OCL_DEVICE_NO_CACHE =  0;
  OCL_DEVICE_READ_ONLY_CACHE =  1;
  OCL_DEVICE_READ_WRITE_CACHE =  2;
  OCL_DEVICE_NO_LOCAL_MEM =  0;
  OCL_DEVICE_LOCAL_IS_LOCAL =  1;
  OCL_DEVICE_LOCAL_IS_GLOBAL =  2;
  OCL_DEVICE_UNKNOWN_VENDOR =  0;
  OCL_DEVICE_VENDOR_AMD =  1;
  OCL_DEVICE_VENDOR_INTEL =  2;
  OCL_DEVICE_VENDOR_NVIDIA =  3;
  OCL_KERNELARG_LOCAL =  1;
  OCL_KERNELARG_READ_ONLY =  2;
  OCL_KERNELARG_WRITE_ONLY =  4;
  OCL_KERNELARG_READ_WRITE =  6;
  OCL_KERNELARG_CONSTANT =  8;
  OCL_KERNELARG_PTR_ONLY =  16;
  OCL_KERNELARG_NO_SIZE =  256;
Type
  TCvocl_OclVectorStrategy = (  OCL_VECTOR_OWN =  0,  OCL_VECTOR_MAX =  1,  OCL_VECTOR_DEFAULT =  OCL_VECTOR_OWN  );
  TCvFileStorage_Mode = (  _READ =  0,  _WRITE =  1,  _APPEND =  2,
          MEMORY =  4,  FORMAT_MASK =  (7 shl 3),  FORMAT_AUTO =  0,
          FORMAT_XML =  (1 shl 3),  FORMAT_YAML =  (2 shl 3),  FORMAT_JSON =  (3 shl 3),
          BASE64 =  64,  WRITE_BASE64 =  ord(BASE64)  or  ord(_WRITE)  );
  TCvFileStorage_State = (  UNDEFINED =  0,  VALUE_EXPECTED =  1,  NAME_EXPECTED =  2,
          INSIDE_MAP =  4  );
Const
  FILENODE_NONE =  0;
  FILENODE_INT =  1;
  FILENODE_REAL =  2;
  FILENODE_FLOAT =  _REAL;
  FILENODE_STR =  3;
  FILENODE_STRING =  FileNode_STR;
  FILENODE_SEQ =  4;
  FILENODE_MAP =  5;
  FILENODE_TYPE_MASK =  7;
  FILENODE_FLOW =  8;
  FILENODE_UNIFORM =  8;
  FILENODE_EMPTY =  16;
  FILENODE_NAMED =  32;
Type
  TCvTermCriteria_Type = (  COUNT =  1,  MAX_ITER =  COUNT,  EPS =  2  );
  TCvdnn_Backend = (  DNN_BACKEND_DEFAULT =  0,  DNN_BACKEND_HALIDE =  0+1,  DNN_BACKEND_INFERENCE_ENGINE =  0+2,
          DNN_BACKEND_OPENCV =  0+3,  DNN_BACKEND_VKCOM =  0+4,  DNN_BACKEND_CUDA =  0+5,
          DNN_BACKEND_WEBNN =  0+6,  DNN_BACKEND_TIMVX =  0+7  );
  TCvdnn_Target = (  DNN_TARGET_CPU =  0,  DNN_TARGET_OPENCL =  0+1,  DNN_TARGET_OPENCL_FP16 =  0+2,
          DNN_TARGET_MYRIAD =  0+3,  DNN_TARGET_VULKAN =  0+4,  DNN_TARGET_FPGA =  0+5,
          DNN_TARGET_CUDA =  0+6,  DNN_TARGET_CUDA_FP16 =  0+7,  DNN_TARGET_HDDL =  0+8,
          DNN_TARGET_NPU =  0+9  );
  TCvdnn_SoftNMSMethod = (  _SOFTNMS_LINEAR =  1,  _SOFTNMS_GAUSSIAN =  2  );
  TCvORB_ScoreType = (  HARRIS_SCORE =  0,  FAST_SCORE =  1  );
  TCvFastFeatureDetector_DetectorType = (  TYPE_5_8 =  0,  TYPE_7_12 =  1,  TYPE_9_16 =  2  );
Const
  FASTFEATUREDETECTOR_THRESHOLD =  10000;
  FASTFEATUREDETECTOR_NONMAX_SUPPRESSION =  10001;
  FASTFEATUREDETECTOR_FAST_N =  10002;
Type
  TCvAgastFeatureDetector_DetectorType = (  AGAST_5_8 =  0,  AGAST_7_12D =  1,  AGAST_7_12S =  2,
          OAST_9_16 =  3  );
Const
  AGASTFEATUREDETECTOR_THRESHOLD =  10000;
  AGASTFEATUREDETECTOR_NONMAX_SUPPRESSION =  10001;
Type
  TCvKAZE_DiffusivityType = (  DIFF_PM_G1 =  0,  DIFF_PM_G2 =  1,  DIFF_WEICKERT =  2,
          DIFF_CHARBONNIER =  3  );
  TCvAKAZE_DescriptorType = (  DESCRIPTOR_KAZE_UPRIGHT =  2,  DESCRIPTOR_KAZE =  3,  DESCRIPTOR_MLDB_UPRIGHT =  4,
          DESCRIPTOR_MLDB =  5  );
  TCvDescriptorMatcher_MatcherType = (  FLANNBASED =  1,  BRUTEFORCE =  2,  BRUTEFORCE_L1 =  3,
          BRUTEFORCE_HAMMING =  4,  BRUTEFORCE_HAMMINGLUT =  5,  BRUTEFORCE_SL2 =  6  );
  TCvDrawMatchesFlags = (  _DEFAULT =  0,  _DRAW_OVER_OUTIMG =  1,  _NOT_DRAW_SINGLE_POINTS =  2,
          _DRAW_RICH_KEYPOINTS =  4  );
  TCvcvflann_flann_algorithm_t = (  FLANN_INDEX_LINEAR =  0,  FLANN_INDEX_KDTREE =  1,  FLANN_INDEX_KMEANS =  2,
          FLANN_INDEX_COMPOSITE =  3,  FLANN_INDEX_KDTREE_SINGLE =  4,  FLANN_INDEX_HIERARCHICAL =  5,
          FLANN_INDEX_LSH =  6,  FLANN_INDEX_SAVED =  254,  FLANN_INDEX_AUTOTUNED =  255,
          LINEAR =  0,  KDTREE =  1,  KMEANS =  2,
          COMPOSITE =  3,  KDTREE_SINGLE =  4,  SAVED =  254,
          AUTOTUNED =  255  );
  TCvcvflann_flann_centers_init_t = (  FLANN_CENTERS_RANDOM =  0,  FLANN_CENTERS_GONZALES =  1,  FLANN_CENTERS_KMEANSPP =  2,
          FLANN_CENTERS_GROUPWISE =  3,  CENTERS_RANDOM =  0,  CENTERS_GONZALES =  1,
          CENTERS_KMEANSPP =  2  );
  TCvcvflann_flann_log_level_t = (  FLANN_LOG_NONE =  0,  FLANN_LOG_FATAL =  1,  FLANN_LOG_ERROR =  2,
          FLANN_LOG_WARN =  3,  FLANN_LOG_INFO =  4  );
  TCvcvflann_flann_distance_t = (  FLANN_DIST_EUCLIDEAN =  1,  FLANN_DIST_L2 =  1,  FLANN_DIST_MANHATTAN =  2,
          FLANN_DIST_L1 =  2,  FLANN_DIST_MINKOWSKI =  3,  FLANN_DIST_MAX =  4,
          FLANN_DIST_HIST_INTERSECT =  5,  FLANN_DIST_HELLINGER =  6,  FLANN_DIST_CHI_SQUARE =  7,
          FLANN_DIST_CS =  7,  FLANN_DIST_KULLBACK_LEIBLER =  8,  FLANN_DIST_KL =  8,
          FLANN_DIST_HAMMING =  9,  FLANN_DIST_DNAMMING =  10,  EUCLIDEAN =  1,
          MANHATTAN =  2,  MINKOWSKI =  3,  MAX_DIST =  4,
          HIST_INTERSECT =  5,  HELLINGER =  6,  CS =  7,
          KL =  8,  KULLBACK_LEIBLER =  8  );
  TCvcvflann_flann_datatype_t = (  FLANN_INT8 =  0,  FLANN_INT16 =  1,  FLANN_INT32 =  2,
          FLANN_INT64 =  3,  FLANN_UINT8 =  4,  FLANN_UINT16 =  5,
          FLANN_UINT32 =  6,  FLANN_UINT64 =  7,  FLANN_FLOAT32 =  8,
          FLANN_FLOAT64 =  9  );
Const
  CVFLANN_FLANN_CHECKS_UNLIMITED =  -1;
  CVFLANN_FLANN_CHECKS_AUTOTUNED =  -2;
Type
  TCvflann_FlannIndexType = (  FLANN_INDEX_TYPE_8U =  CV_8U,  FLANN_INDEX_TYPE_8S =  CV_8S,  FLANN_INDEX_TYPE_16U =  CV_16U,
          FLANN_INDEX_TYPE_16S =  CV_16S,  FLANN_INDEX_TYPE_32S =  CV_32S,  FLANN_INDEX_TYPE_32F =  CV_32F,
          FLANN_INDEX_TYPE_64F =  CV_64F,  FLANN_INDEX_TYPE_STRING =  CV_64F+1,  FLANN_INDEX_TYPE_BOOL =  CV_64F+2,
          FLANN_INDEX_TYPE_ALGORITHM =  CV_64F+3,  LAST_VALUE_FLANN_INDEX_TYPE =  FLANN_INDEX_TYPE_ALGORITHM  );
  TCvWindowFlags = (  WINDOW_NORMAL =  $00000000,  WINDOW_AUTOSIZE =  $00000001,  WINDOW_OPENGL =  $00001000,
          WINDOW_FULLSCREEN =  1,  WINDOW_FREERATIO =  $00000100,  WINDOW_KEEPRATIO =  $00000000,
          WINDOW_GUI_EXPANDED =  $00000000,  WINDOW_GUI_NORMAL =  $00000010  );
  TCvWindowPropertyFlags = (  WND_PROP_FULLSCREEN =  0,  WND_PROP_AUTOSIZE =  1,  WND_PROP_ASPECT_RATIO =  2,
          WND_PROP_OPENGL =  3,  WND_PROP_VISIBLE =  4,  WND_PROP_TOPMOST =  5,
          WND_PROP_VSYNC =  6  );
  TCvMouseEventTypes = (  EVENT_MOUSEMOVE =  0,  EVENT_LBUTTONDOWN =  1,  EVENT_RBUTTONDOWN =  2,
          EVENT_MBUTTONDOWN =  3,  EVENT_LBUTTONUP =  4,  EVENT_RBUTTONUP =  5,
          EVENT_MBUTTONUP =  6,  EVENT_LBUTTONDBLCLK =  7,  EVENT_RBUTTONDBLCLK =  8,
          EVENT_MBUTTONDBLCLK =  9,  EVENT_MOUSEWHEEL =  10,  EVENT_MOUSEHWHEEL =  11  );
  TCvMouseEventFlags = (  EVENT_FLAG_LBUTTON =  1,  EVENT_FLAG_RBUTTON =  2,  EVENT_FLAG_MBUTTON =  4,
          EVENT_FLAG_CTRLKEY =  8,  EVENT_FLAG_SHIFTKEY =  16,  EVENT_FLAG_ALTKEY =  32  );
  TCvQtFontWeights = (  QT_FONT_LIGHT =  25,  QT_FONT_NORMAL =  50,  QT_FONT_DEMIBOLD =  63,
          QT_FONT_BOLD =  75,  QT_FONT_BLACK =  87  );
  TCvQtFontStyles = (  QT_STYLE_NORMAL =  0,  QT_STYLE_ITALIC =  1,  QT_STYLE_OBLIQUE =  2  );
  TCvQtButtonTypes = (  QT_PUSH_BUTTON =  0,  QT_CHECKBOX =  1,  QT_RADIOBOX =  2,
          QT_NEW_BUTTONBAR =  1024  );
  TCvImreadModes = (  IMREAD_UNCHANGED =  -1,  IMREAD_GRAYSCALE =  0,  IMREAD_COLOR =  1,
          IMREAD_ANYDEPTH =  2,  IMREAD_ANYCOLOR =  4,  IMREAD_LOAD_GDAL =  8,
          IMREAD_REDUCED_GRAYSCALE_2 =  16,  IMREAD_REDUCED_COLOR_2 =  17,  IMREAD_REDUCED_GRAYSCALE_4 =  32,
          IMREAD_REDUCED_COLOR_4 =  33,  IMREAD_REDUCED_GRAYSCALE_8 =  64,  IMREAD_REDUCED_COLOR_8 =  65,
          IMREAD_IGNORE_ORIENTATION =  128  );
  TCvImwriteFlags = (  IMWRITE_JPEG_QUALITY =  1,  IMWRITE_JPEG_PROGRESSIVE =  2,  IMWRITE_JPEG_OPTIMIZE =  3,
          IMWRITE_JPEG_RST_INTERVAL =  4,  IMWRITE_JPEG_LUMA_QUALITY =  5,  IMWRITE_JPEG_CHROMA_QUALITY =  6,
          IMWRITE_PNG_COMPRESSION =  16,  IMWRITE_PNG_STRATEGY =  17,  IMWRITE_PNG_BILEVEL =  18,
          IMWRITE_PXM_BINARY =  32,  IMWRITE_EXR_TYPE =  (3  shl  4) + 0,  IMWRITE_EXR_COMPRESSION =  (3  shl  4) + 1,
          IMWRITE_WEBP_QUALITY =  64,  IMWRITE_PAM_TUPLETYPE =  128,  IMWRITE_TIFF_RESUNIT =  256,
          IMWRITE_TIFF_XDPI =  257,  IMWRITE_TIFF_YDPI =  258,  IMWRITE_TIFF_COMPRESSION =  259,
          IMWRITE_JPEG2000_COMPRESSION_X1000 =  272  );
  TCvImwriteEXRTypeFlags = (  IMWRITE_EXR_TYPE_HALF =  1,  IMWRITE_EXR_TYPE_FLOAT =  2  );
  TCvImwriteEXRCompressionFlags = (  IMWRITE_EXR_COMPRESSION_NO =  0,  IMWRITE_EXR_COMPRESSION_RLE =  1,  IMWRITE_EXR_COMPRESSION_ZIPS =  2,
          IMWRITE_EXR_COMPRESSION_ZIP =  3,  IMWRITE_EXR_COMPRESSION_PIZ =  4,  IMWRITE_EXR_COMPRESSION_PXR24 =  5,
          IMWRITE_EXR_COMPRESSION_B44 =  6,  IMWRITE_EXR_COMPRESSION_B44A =  7,  IMWRITE_EXR_COMPRESSION_DWAA =  8,
          IMWRITE_EXR_COMPRESSION_DWAB =  9  );
  TCvImwritePNGFlags = (  IMWRITE_PNG_STRATEGY_DEFAULT =  0,  IMWRITE_PNG_STRATEGY_FILTERED =  1,  IMWRITE_PNG_STRATEGY_HUFFMAN_ONLY =  2,
          IMWRITE_PNG_STRATEGY_RLE =  3,  IMWRITE_PNG_STRATEGY_FIXED =  4  );
  TCvImwritePAMFlags = (  IMWRITE_PAM_FORMAT_NULL =  0,  IMWRITE_PAM_FORMAT_BLACKANDWHITE =  1,  IMWRITE_PAM_FORMAT_GRAYSCALE =  2,
          IMWRITE_PAM_FORMAT_GRAYSCALE_ALPHA =  3,  IMWRITE_PAM_FORMAT_RGB =  4,  IMWRITE_PAM_FORMAT_RGB_ALPHA =  5  );
  TCvSpecialFilter = (  FILTER_SCHARR =  -1  );
  TCvMorphTypes = (  MORPH_ERODE =  0,  MORPH_DILATE =  1,  MORPH_OPEN =  2,
          MORPH_CLOSE =  3,  MORPH_GRADIENT =  4,  MORPH_TOPHAT =  5,
          MORPH_BLACKHAT =  6,  MORPH_HITMISS =  7  );
  TCvMorphShapes = (  MORPH_RECT =  0,  MORPH_CROSS =  1,  MORPH_ELLIPSE =  2  );
  TCvInterpolationFlags = (  INTER_NEAREST =  0,  INTER_LINEAR =  1,  INTER_CUBIC =  2,
          INTER_AREA =  3,  INTER_LANCZOS4 =  4,  INTER_LINEAR_EXACT =  5,
          INTER_NEAREST_EXACT =  6,  INTER_MAX =  7,  WARP_FILL_OUTLIERS =  8,
          WARP_INVERSE_MAP =  16  );
  TCvWarpPolarMode = (  WARP_POLAR_LINEAR =  0,  WARP_POLAR_LOG =  256  );
  TCvInterpolationMasks = (  INTER_BITS =  5,  INTER_BITS2 =  INTER_BITS * 2,  INTER_TAB_SIZE =  1  shl  ord(INTER_BITS),
          INTER_TAB_SIZE2 =  ord(INTER_TAB_SIZE) * ord(INTER_TAB_SIZE)  );
  TCvDistanceTypes = (  DIST_USER =  -1,  DIST_L1 =  1,  DIST_L2 =  2,
          DIST_C =  3,  DIST_L12 =  4,  DIST_FAIR =  5,
          DIST_WELSCH =  6,  DIST_HUBER =  7  );
  TCvDistanceTransformMasks = (  DIST_MASK_3 =  3,  DIST_MASK_5 =  5,  DIST_MASK_PRECISE =  0  );
  TCvThresholdTypes = (  THRESH_BINARY =  0,  THRESH_BINARY_INV =  1,  THRESH_TRUNC =  2,
          THRESH_TOZERO =  3,  THRESH_TOZERO_INV =  4,  THRESH_MASK =  7,
          THRESH_OTSU =  8,  THRESH_TRIANGLE =  16  );
  TCvAdaptiveThresholdTypes = (  ADAPTIVE_THRESH_MEAN_C =  0,  ADAPTIVE_THRESH_GAUSSIAN_C =  1  );
  TCvGrabCutClasses = (  GC_BGD =  0,  GC_FGD =  1,  GC_PR_BGD =  2,
          GC_PR_FGD =  3  );
  TCvGrabCutModes = (  GC_INIT_WITH_RECT =  0,  GC_INIT_WITH_MASK =  1,  GC_EVAL =  2,
          GC_EVAL_FREEZE_MODEL =  3  );
  TCvDistanceTransformLabelTypes = (  DIST_LABEL_CCOMP =  0,  DIST_LABEL_PIXEL =  1  );
  TCvFloodFillFlags = (  FLOODFILL_FIXED_RANGE =  1  shl  16,  FLOODFILL_MASK_ONLY =  1  shl  17  );
  TCvConnectedComponentsTypes = (  CC_STAT_LEFT =  0,  CC_STAT_TOP =  1,  CC_STAT_WIDTH =  2,
          CC_STAT_HEIGHT =  3,  CC_STAT_AREA =  4,  CC_STAT_MAX =  5  );
  TCvConnectedComponentsAlgorithmsTypes = (  CCL_DEFAULT =  -1,  CCL_WU =  0,  CCL_GRANA =  1,
          CCL_BOLELLI =  2,  CCL_SAUF =  3,  CCL_BBDT =  4,
          CCL_SPAGHETTI =  5  );
  TCvRetrievalModes = (  RETR_EXTERNAL =  0,  RETR_LIST =  1,  RETR_CCOMP =  2,
          RETR_TREE =  3,  RETR_FLOODFILL =  4  );
  TCvContourApproximationModes = (  CHAIN_APPROX_NONE =  1,  CHAIN_APPROX_SIMPLE =  2,  CHAIN_APPROX_TC89_L1 =  3,
          CHAIN_APPROX_TC89_KCOS =  4  );
  TCvShapeMatchModes = (  CONTOURS_MATCH_I1 =  1,  CONTOURS_MATCH_I2 =  2,  CONTOURS_MATCH_I3 =  3  );
  TCvHoughModes = (  HOUGH_STANDARD =  0,  HOUGH_PROBABILISTIC =  1,  HOUGH_MULTI_SCALE =  2,
          HOUGH_GRADIENT =  3,  HOUGH_GRADIENT_ALT =  4  );
  TCvLineSegmentDetectorModes = (  LSD_REFINE_NONE =  0,  LSD_REFINE_STD =  1,  LSD_REFINE_ADV =  2  );
  TCvHistCompMethods = (  HISTCMP_CORREL =  0,  HISTCMP_CHISQR =  1,  HISTCMP_INTERSECT =  2,
          HISTCMP_BHATTACHARYYA =  3,  HISTCMP_HELLINGER =  HISTCMP_BHATTACHARYYA,  HISTCMP_CHISQR_ALT =  4,
          HISTCMP_KL_DIV =  5  );
  TCvColorConversionCodes = (  COLOR_BGR2BGRA =  0,  COLOR_RGB2RGBA =  COLOR_BGR2BGRA,  COLOR_BGRA2BGR =  1,
          COLOR_RGBA2RGB =  COLOR_BGRA2BGR,  COLOR_BGR2RGBA =  2,  COLOR_RGB2BGRA =  COLOR_BGR2RGBA,
          COLOR_RGBA2BGR =  3,  COLOR_BGRA2RGB =  COLOR_RGBA2BGR,  COLOR_BGR2RGB =  4,
          COLOR_RGB2BGR =  COLOR_BGR2RGB,  COLOR_BGRA2RGBA =  5,  COLOR_RGBA2BGRA =  COLOR_BGRA2RGBA,
          COLOR_BGR2GRAY =  6,  COLOR_RGB2GRAY =  7,  COLOR_GRAY2BGR =  8,
          COLOR_GRAY2RGB =  COLOR_GRAY2BGR,  COLOR_GRAY2BGRA =  9,  COLOR_GRAY2RGBA =  COLOR_GRAY2BGRA,
          COLOR_BGRA2GRAY =  10,  COLOR_RGBA2GRAY =  11,  COLOR_BGR2BGR565 =  12,
          COLOR_RGB2BGR565 =  13,  COLOR_BGR5652BGR =  14,  COLOR_BGR5652RGB =  15,
          COLOR_BGRA2BGR565 =  16,  COLOR_RGBA2BGR565 =  17,  COLOR_BGR5652BGRA =  18,
          COLOR_BGR5652RGBA =  19,  COLOR_GRAY2BGR565 =  20,  COLOR_BGR5652GRAY =  21,
          COLOR_BGR2BGR555 =  22,  COLOR_RGB2BGR555 =  23,  COLOR_BGR5552BGR =  24,
          COLOR_BGR5552RGB =  25,  COLOR_BGRA2BGR555 =  26,  COLOR_RGBA2BGR555 =  27,
          COLOR_BGR5552BGRA =  28,  COLOR_BGR5552RGBA =  29,  COLOR_GRAY2BGR555 =  30,
          COLOR_BGR5552GRAY =  31,  COLOR_BGR2XYZ =  32,  COLOR_RGB2XYZ =  33,
          COLOR_XYZ2BGR =  34,  COLOR_XYZ2RGB =  35,  COLOR_BGR2YCRCB =  36,
          COLOR_RGB2YCRCB =  37,  COLOR_YCRCB2BGR =  38,  COLOR_YCRCB2RGB =  39,
          COLOR_BGR2HSV =  40,  COLOR_RGB2HSV =  41,  COLOR_BGR2LAB =  44,
          COLOR_RGB2LAB =  45,  COLOR_BGR2LUV =  50,  COLOR_RGB2LUV =  51,
          COLOR_BGR2HLS =  52,  COLOR_RGB2HLS =  53,  COLOR_HSV2BGR =  54,
          COLOR_HSV2RGB =  55,  COLOR_LAB2BGR =  56,  COLOR_LAB2RGB =  57,
          COLOR_LUV2BGR =  58,  COLOR_LUV2RGB =  59,  COLOR_HLS2BGR =  60,
          COLOR_HLS2RGB =  61,  COLOR_BGR2HSV_FULL =  66,  COLOR_RGB2HSV_FULL =  67,
          COLOR_BGR2HLS_FULL =  68,  COLOR_RGB2HLS_FULL =  69,  COLOR_HSV2BGR_FULL =  70,
          COLOR_HSV2RGB_FULL =  71,  COLOR_HLS2BGR_FULL =  72,  COLOR_HLS2RGB_FULL =  73,
          COLOR_LBGR2LAB =  74,  COLOR_LRGB2LAB =  75,  COLOR_LBGR2LUV =  76,
          COLOR_LRGB2LUV =  77,  COLOR_LAB2LBGR =  78,  COLOR_LAB2LRGB =  79,
          COLOR_LUV2LBGR =  80,  COLOR_LUV2LRGB =  81,  COLOR_BGR2YUV =  82,
          COLOR_RGB2YUV =  83,  COLOR_YUV2BGR =  84,  COLOR_YUV2RGB =  85,
          COLOR_YUV2RGB_NV12 =  90,  COLOR_YUV2BGR_NV12 =  91,  COLOR_YUV2RGB_NV21 =  92,
          COLOR_YUV2BGR_NV21 =  93,  COLOR_YUV420SP2RGB =  COLOR_YUV2RGB_NV21,  COLOR_YUV420SP2BGR =  COLOR_YUV2BGR_NV21,
          COLOR_YUV2RGBA_NV12 =  94,  COLOR_YUV2BGRA_NV12 =  95,  COLOR_YUV2RGBA_NV21 =  96,
          COLOR_YUV2BGRA_NV21 =  97,  COLOR_YUV420SP2RGBA =  COLOR_YUV2RGBA_NV21,  COLOR_YUV420SP2BGRA =  COLOR_YUV2BGRA_NV21,
          COLOR_YUV2RGB_YV12 =  98,  COLOR_YUV2BGR_YV12 =  99,  COLOR_YUV2RGB_IYUV =  100,
          COLOR_YUV2BGR_IYUV =  101,  COLOR_YUV2RGB_I420 =  COLOR_YUV2RGB_IYUV,  COLOR_YUV2BGR_I420 =  COLOR_YUV2BGR_IYUV,
          COLOR_YUV420P2RGB =  COLOR_YUV2RGB_YV12,  COLOR_YUV420P2BGR =  COLOR_YUV2BGR_YV12,  COLOR_YUV2RGBA_YV12 =  102,
          COLOR_YUV2BGRA_YV12 =  103,  COLOR_YUV2RGBA_IYUV =  104,  COLOR_YUV2BGRA_IYUV =  105,
          COLOR_YUV2RGBA_I420 =  COLOR_YUV2RGBA_IYUV,  COLOR_YUV2BGRA_I420 =  COLOR_YUV2BGRA_IYUV,  COLOR_YUV420P2RGBA =  COLOR_YUV2RGBA_YV12,
          COLOR_YUV420P2BGRA =  COLOR_YUV2BGRA_YV12,  COLOR_YUV2GRAY_420 =  106,  COLOR_YUV2GRAY_NV21 =  COLOR_YUV2GRAY_420,
          COLOR_YUV2GRAY_NV12 =  COLOR_YUV2GRAY_420,  COLOR_YUV2GRAY_YV12 =  COLOR_YUV2GRAY_420,  COLOR_YUV2GRAY_IYUV =  COLOR_YUV2GRAY_420,
          COLOR_YUV2GRAY_I420 =  COLOR_YUV2GRAY_420,  COLOR_YUV420SP2GRAY =  COLOR_YUV2GRAY_420,  COLOR_YUV420P2GRAY =  COLOR_YUV2GRAY_420,
          COLOR_YUV2RGB_UYVY =  107,  COLOR_YUV2BGR_UYVY =  108,  COLOR_YUV2RGB_Y422 =  COLOR_YUV2RGB_UYVY,
          COLOR_YUV2BGR_Y422 =  COLOR_YUV2BGR_UYVY,  COLOR_YUV2RGB_UYNV =  COLOR_YUV2RGB_UYVY,  COLOR_YUV2BGR_UYNV =  COLOR_YUV2BGR_UYVY,
          COLOR_YUV2RGBA_UYVY =  111,  COLOR_YUV2BGRA_UYVY =  112,  COLOR_YUV2RGBA_Y422 =  COLOR_YUV2RGBA_UYVY,
          COLOR_YUV2BGRA_Y422 =  COLOR_YUV2BGRA_UYVY,  COLOR_YUV2RGBA_UYNV =  COLOR_YUV2RGBA_UYVY,  COLOR_YUV2BGRA_UYNV =  COLOR_YUV2BGRA_UYVY,
          COLOR_YUV2RGB_YUY2 =  115,  COLOR_YUV2BGR_YUY2 =  116,  COLOR_YUV2RGB_YVYU =  117,
          COLOR_YUV2BGR_YVYU =  118,  COLOR_YUV2RGB_YUYV =  COLOR_YUV2RGB_YUY2,  COLOR_YUV2BGR_YUYV =  COLOR_YUV2BGR_YUY2,
          COLOR_YUV2RGB_YUNV =  COLOR_YUV2RGB_YUY2,  COLOR_YUV2BGR_YUNV =  COLOR_YUV2BGR_YUY2,  COLOR_YUV2RGBA_YUY2 =  119,
          COLOR_YUV2BGRA_YUY2 =  120,  COLOR_YUV2RGBA_YVYU =  121,  COLOR_YUV2BGRA_YVYU =  122,
          COLOR_YUV2RGBA_YUYV =  COLOR_YUV2RGBA_YUY2,  COLOR_YUV2BGRA_YUYV =  COLOR_YUV2BGRA_YUY2,  COLOR_YUV2RGBA_YUNV =  COLOR_YUV2RGBA_YUY2,
          COLOR_YUV2BGRA_YUNV =  COLOR_YUV2BGRA_YUY2,  COLOR_YUV2GRAY_UYVY =  123,  COLOR_YUV2GRAY_YUY2 =  124,
          COLOR_YUV2GRAY_Y422 =  COLOR_YUV2GRAY_UYVY,  COLOR_YUV2GRAY_UYNV =  COLOR_YUV2GRAY_UYVY,  COLOR_YUV2GRAY_YVYU =  COLOR_YUV2GRAY_YUY2,
          COLOR_YUV2GRAY_YUYV =  COLOR_YUV2GRAY_YUY2,  COLOR_YUV2GRAY_YUNV =  COLOR_YUV2GRAY_YUY2,  COLOR_RGBA2MRGBA =  125,
          COLOR_MRGBA2RGBA =  126,  COLOR_RGB2YUV_I420 =  127,  COLOR_BGR2YUV_I420 =  128,
          COLOR_RGB2YUV_IYUV =  COLOR_RGB2YUV_I420,  COLOR_BGR2YUV_IYUV =  COLOR_BGR2YUV_I420,  COLOR_RGBA2YUV_I420 =  129,
          COLOR_BGRA2YUV_I420 =  130,  COLOR_RGBA2YUV_IYUV =  COLOR_RGBA2YUV_I420,  COLOR_BGRA2YUV_IYUV =  COLOR_BGRA2YUV_I420,
          COLOR_RGB2YUV_YV12 =  131,  COLOR_BGR2YUV_YV12 =  132,  COLOR_RGBA2YUV_YV12 =  133,
          COLOR_BGRA2YUV_YV12 =  134,  COLOR_BAYERBG2BGR =  46,  COLOR_BAYERGB2BGR =  47,
          COLOR_BAYERRG2BGR =  48,  COLOR_BAYERGR2BGR =  49,  COLOR_BAYERRGGB2BGR =  COLOR_BayerBG2BGR,
          COLOR_BAYERGRBG2BGR =  COLOR_BayerGB2BGR,  COLOR_BAYERBGGR2BGR =  COLOR_BayerRG2BGR,  COLOR_BAYERGBRG2BGR =  COLOR_BayerGR2BGR,
          COLOR_BAYERRGGB2RGB =  COLOR_BayerBGGR2BGR,  COLOR_BAYERGRBG2RGB =  COLOR_BayerGBRG2BGR,  COLOR_BAYERBGGR2RGB =  COLOR_BayerRGGB2BGR,
          COLOR_BAYERGBRG2RGB =  COLOR_BayerGRBG2BGR,  COLOR_BAYERBG2RGB =  COLOR_BayerRG2BGR,  COLOR_BAYERGB2RGB =  COLOR_BayerGR2BGR,
          COLOR_BAYERRG2RGB =  COLOR_BayerBG2BGR,  COLOR_BAYERGR2RGB =  COLOR_BayerGB2BGR,  COLOR_BAYERBG2GRAY =  86,
          COLOR_BAYERGB2GRAY =  87,  COLOR_BAYERRG2GRAY =  88,  COLOR_BAYERGR2GRAY =  89,
          COLOR_BAYERRGGB2GRAY =  COLOR_BayerBG2GRAY,  COLOR_BAYERGRBG2GRAY =  COLOR_BayerGB2GRAY,  COLOR_BAYERBGGR2GRAY =  COLOR_BayerRG2GRAY,
          COLOR_BAYERGBRG2GRAY =  COLOR_BayerGR2GRAY,  COLOR_BAYERBG2BGR_VNG =  62,  COLOR_BAYERGB2BGR_VNG =  63,
          COLOR_BAYERRG2BGR_VNG =  64,  COLOR_BAYERGR2BGR_VNG =  65,  COLOR_BAYERRGGB2BGR_VNG =  COLOR_BayerBG2BGR_VNG,
          COLOR_BAYERGRBG2BGR_VNG =  COLOR_BayerGB2BGR_VNG,  COLOR_BAYERBGGR2BGR_VNG =  COLOR_BayerRG2BGR_VNG,  COLOR_BAYERGBRG2BGR_VNG =  COLOR_BayerGR2BGR_VNG,
          COLOR_BAYERRGGB2RGB_VNG =  COLOR_BayerBGGR2BGR_VNG,  COLOR_BAYERGRBG2RGB_VNG =  COLOR_BayerGBRG2BGR_VNG,  COLOR_BAYERBGGR2RGB_VNG =  COLOR_BayerRGGB2BGR_VNG,
          COLOR_BAYERGBRG2RGB_VNG =  COLOR_BayerGRBG2BGR_VNG,  COLOR_BAYERBG2RGB_VNG =  COLOR_BayerRG2BGR_VNG,  COLOR_BAYERGB2RGB_VNG =  COLOR_BayerGR2BGR_VNG,
          COLOR_BAYERRG2RGB_VNG =  COLOR_BayerBG2BGR_VNG,  COLOR_BAYERGR2RGB_VNG =  COLOR_BayerGB2BGR_VNG,  COLOR_BAYERBG2BGR_EA =  135,
          COLOR_BAYERGB2BGR_EA =  136,  COLOR_BAYERRG2BGR_EA =  137,  COLOR_BAYERGR2BGR_EA =  138,
          COLOR_BAYERRGGB2BGR_EA =  COLOR_BayerBG2BGR_EA,  COLOR_BAYERGRBG2BGR_EA =  COLOR_BayerGB2BGR_EA,  COLOR_BAYERBGGR2BGR_EA =  COLOR_BayerRG2BGR_EA,
          COLOR_BAYERGBRG2BGR_EA =  COLOR_BayerGR2BGR_EA,  COLOR_BAYERRGGB2RGB_EA =  COLOR_BayerBGGR2BGR_EA,  COLOR_BAYERGRBG2RGB_EA =  COLOR_BayerGBRG2BGR_EA,
          COLOR_BAYERBGGR2RGB_EA =  COLOR_BayerRGGB2BGR_EA,  COLOR_BAYERGBRG2RGB_EA =  COLOR_BayerGRBG2BGR_EA,  COLOR_BAYERBG2RGB_EA =  COLOR_BayerRG2BGR_EA,
          COLOR_BAYERGB2RGB_EA =  COLOR_BayerGR2BGR_EA,  COLOR_BAYERRG2RGB_EA =  COLOR_BayerBG2BGR_EA,  COLOR_BAYERGR2RGB_EA =  COLOR_BayerGB2BGR_EA,
          COLOR_BAYERBG2BGRA =  139,  COLOR_BAYERGB2BGRA =  140,  COLOR_BAYERRG2BGRA =  141,
          COLOR_BAYERGR2BGRA =  142,  COLOR_BAYERRGGB2BGRA =  COLOR_BayerBG2BGRA,  COLOR_BAYERGRBG2BGRA =  COLOR_BayerGB2BGRA,
          COLOR_BAYERBGGR2BGRA =  COLOR_BayerRG2BGRA,  COLOR_BAYERGBRG2BGRA =  COLOR_BayerGR2BGRA,  COLOR_BAYERRGGB2RGBA =  COLOR_BayerBGGR2BGRA,
          COLOR_BAYERGRBG2RGBA =  COLOR_BayerGBRG2BGRA,  COLOR_BAYERBGGR2RGBA =  COLOR_BayerRGGB2BGRA,  COLOR_BAYERGBRG2RGBA =  COLOR_BayerGRBG2BGRA,
          COLOR_BAYERBG2RGBA =  COLOR_BayerRG2BGRA,  COLOR_BAYERGB2RGBA =  COLOR_BayerGR2BGRA,  COLOR_BAYERRG2RGBA =  COLOR_BayerBG2BGRA,
          COLOR_BAYERGR2RGBA =  COLOR_BayerGB2BGRA,  COLOR_COLORCVT_MAX =  143  );
  TCvRectanglesIntersectTypes = (  INTERSECT_NONE =  0,  INTERSECT_PARTIAL =  1,  INTERSECT_FULL =  2  );
  TCvHersheyFonts = (  FONT_HERSHEY_SIMPLEX =  0,  FONT_HERSHEY_PLAIN =  1,  FONT_HERSHEY_DUPLEX =  2,
          FONT_HERSHEY_COMPLEX =  3,  FONT_HERSHEY_TRIPLEX =  4,  FONT_HERSHEY_COMPLEX_SMALL =  5,
          FONT_HERSHEY_SCRIPT_SIMPLEX =  6,  FONT_HERSHEY_SCRIPT_COMPLEX =  7,  FONT_ITALIC =  16  );
  TCvMarkerTypes = (  MARKER_CROSS =  0,  MARKER_TILTED_CROSS =  1,  MARKER_STAR =  2,
          MARKER_DIAMOND =  3,  MARKER_SQUARE =  4,  MARKER_TRIANGLE_UP =  5,
          MARKER_TRIANGLE_DOWN =  6  );
Const
  SUBDIV2D_PTLOC_ERROR =  -2;
  SUBDIV2D_PTLOC_OUTSIDE_RECT =  -1;
  SUBDIV2D_PTLOC_INSIDE =  0;
  SUBDIV2D_PTLOC_VERTEX =  1;
  SUBDIV2D_PTLOC_ON_EDGE =  2;
  SUBDIV2D_NEXT_AROUND_ORG =  $00;
  SUBDIV2D_NEXT_AROUND_DST =  $22;
  SUBDIV2D_PREV_AROUND_ORG =  $11;
  SUBDIV2D_PREV_AROUND_DST =  $33;
  SUBDIV2D_NEXT_AROUND_LEFT =  $13;
  SUBDIV2D_NEXT_AROUND_RIGHT =  $31;
  SUBDIV2D_PREV_AROUND_LEFT =  $20;
  SUBDIV2D_PREV_AROUND_RIGHT =  $02;
Type
  TCvTemplateMatchModes = (  TM_SQDIFF =  0,  TM_SQDIFF_NORMED =  1,  TM_CCORR =  2,
          TM_CCORR_NORMED =  3,  TM_CCOEFF =  4,  TM_CCOEFF_NORMED =  5  );
  TCvColormapTypes = (  COLORMAP_AUTUMN =  0,  COLORMAP_BONE =  1,  COLORMAP_JET =  2,
          COLORMAP_WINTER =  3,  COLORMAP_RAINBOW =  4,  COLORMAP_OCEAN =  5,
          COLORMAP_SUMMER =  6,  COLORMAP_SPRING =  7,  COLORMAP_COOL =  8,
          COLORMAP_HSV =  9,  COLORMAP_PINK =  10,  COLORMAP_HOT =  11,
          COLORMAP_PARULA =  12,  COLORMAP_MAGMA =  13,  COLORMAP_INFERNO =  14,
          COLORMAP_PLASMA =  15,  COLORMAP_VIRIDIS =  16,  COLORMAP_CIVIDIS =  17,
          COLORMAP_TWILIGHT =  18,  COLORMAP_TWILIGHT_SHIFTED =  19,  COLORMAP_TURBO =  20,
          COLORMAP_DEEPGREEN =  21  );
  TCvml_VariableTypes = (  VAR_NUMERICAL =  0,  VAR_ORDERED =  0,  VAR_CATEGORICAL =  1  );
  TCvml_ErrorTypes = (  TEST_ERROR =  0,  TRAIN_ERROR =  1  );
  TCvml_SampleTypes = (  ROW_SAMPLE =  0,  COL_SAMPLE =  1  );
  TCvml_StatModel_Flags = (  STATMODEL_UPDATE_MODEL =  1,  STATMODEL_RAW_OUTPUT =  1,  STATMODEL_COMPRESSED_INPUT =  2,
          STATMODEL_PREPROCESSED_INPUT =  4  );
  TCvml_KNearest_Types = (  KNEAREST_BRUTE_FORCE =  1,  KNEAREST_KDTREE =  2  );
  TCvml_SVM_Types = (  SVM_C_SVC =  100,  SVM_NU_SVC =  101,  SVM_ONE_CLASS =  102,
          SVM_EPS_SVR =  103,  SVM_NU_SVR =  104  );
  TCvml_SVM_KernelTypes = (  SVM_CUSTOM =  -1,  SVM_LINEAR =  0,  SVM_POLY =  1,
          SVM_RBF =  2,  SVM_SIGMOID =  3,  SVM_CHI2 =  4,
          SVM_INTER =  5  );
  TCvml_SVM_ParamTypes = (  SVM_C =  0,  SVM_GAMMA =  1,  SVM_P =  2,
          SVM_NU =  3,  SVM_COEF =  4,  SVM_DEGREE =  5  );
  TCvml_EM_Types = (  EM_COV_MAT_SPHERICAL =  0,  EM_COV_MAT_DIAGONAL =  1,  EM_COV_MAT_GENERIC =  2,
          EM_COV_MAT_DEFAULT =  EM_COV_MAT_DIAGONAL  );
Const
  ML_EM_DEFAULT_NCLUSTERS =  5;
  ML_EM_DEFAULT_MAX_ITERS =  100;
  ML_EM_START_E_STEP =  1;
  ML_EM_START_M_STEP =  2;
  ML_EM_START_AUTO_STEP =  0;
Type
  TCvml_DTrees_Flags = (  DTREES_PREDICT_AUTO =  0,  DTREES_PREDICT_SUM =  (1 shl 8),  DTREES_PREDICT_MAX_VOTE =  (2 shl 8),
          DTREES_PREDICT_MASK =  (3 shl 8)  );
  TCvml_Boost_Types = (  BOOST_DISCRETE =  0,  BOOST_REAL =  1,  BOOST_LOGIT =  2,
          BOOST_GENTLE =  3  );
  TCvml_ANN_MLP_TrainingMethods = (  ANN_MLP_BACKPROP =  0,  ANN_MLP_RPROP =  1,  ANN_MLP_ANNEAL =  2  );
  TCvml_ANN_MLP_ActivationFunctions = (  ANN_MLP_IDENTITY =  0,  ANN_MLP_SIGMOID_SYM =  1,  ANN_MLP_GAUSSIAN =  2,
          ANN_MLP_RELU =  3,  ANN_MLP_LEAKYRELU =  4  );
  TCvml_ANN_MLP_TrainFlags = (  ANN_MLP_UPDATE_WEIGHTS =  1,  ANN_MLP_NO_INPUT_SCALE =  2,  ANN_MLP_NO_OUTPUT_SCALE =  4  );
  TCvml_LogisticRegression_RegKinds = (  LOGISTICREGRESSION_REG_DISABLE =  -1,  LOGISTICREGRESSION_REG_L1 =  0,  LOGISTICREGRESSION_REG_L2 =  1  );
  TCvml_LogisticRegression_Methods = (  LOGISTICREGRESSION_BATCH =  0,  LOGISTICREGRESSION_MINI_BATCH =  1  );
  TCvml_SVMSGD_SvmsgdType = (  SVMSGD_SGD =  0,  SVMSGD_ASGD =  1  );
  TCvml_SVMSGD_MarginType = (  SVMSGD_SOFT_MARGIN =  0,  SVMSGD_HARD_MARGIN =  1  );
Const
  CASCADE_DO_CANNY_PRUNING =  1;
  CASCADE_SCALE_IMAGE =  2;
  CASCADE_FIND_BIGGEST_OBJECT =  4;
  CASCADE_DO_ROUGH_SEARCH =  8;
Type
  TCvHOGDescriptor_HistogramNormType = (  L2HYS =  0  );
Const
  HOGDESCRIPTOR_DEFAULT_NLEVELS =  64;
Type
  TCvHOGDescriptor_DescriptorStorageFormat = (  DESCR_FORMAT_COL_BY_COL =  0,  DESCR_FORMAT_ROW_BY_ROW =  1  );
  TCvQRCodeEncoder_EncodeMode = (  MODE_AUTO =  -1,  MODE_NUMERIC =  1,  MODE_ALPHANUMERIC =  2,
          MODE_BYTE =  4,  MODE_ECI =  7,  MODE_KANJI =  8,
          MODE_STRUCTURED_APPEND =  3  );
  TCvQRCodeEncoder_CorrectionLevel = (  CORRECT_LEVEL_L =  0,  CORRECT_LEVEL_M =  1,  CORRECT_LEVEL_Q =  2,
          CORRECT_LEVEL_H =  3  );
  TCvQRCodeEncoder_ECIEncodings = (  ECI_UTF8 =  26  );
  TCvFaceRecognizerSF_DisType = (  FR_COSINE =  0,  FR_NORM_L2 =  1  );
Const
  INPAINT_NS =  0;
  INPAINT_TELEA =  1;
  LDR_SIZE =  256;
  NORMAL_CLONE =  1;
  MIXED_CLONE =  2;
  MONOCHROME_TRANSFER =  3;
  RECURS_FILTER =  1;
  NORMCONV_FILTER =  2;
Type
  TCvStitcher_Status = (  OK =  0,  ERR_NEED_MORE_IMGS =  1,  ERR_HOMOGRAPHY_EST_FAIL =  2,
          ERR_CAMERA_PARAMS_ADJUST_FAIL =  3  );
  TCvStitcher_Mode = (  PANORAMA =  0,  SCANS =  1  );
Const
  DETAIL_BLENDER_NO =  0;
  DETAIL_BLENDER_FEATHER =  1;
  DETAIL_BLENDER_MULTI_BAND =  2;
  DETAIL_EXPOSURECOMPENSATOR_NO =  0;
  DETAIL_EXPOSURECOMPENSATOR_GAIN =  1;
  DETAIL_EXPOSURECOMPENSATOR_GAIN_BLOCKS =  2;
  DETAIL_EXPOSURECOMPENSATOR_CHANNELS =  3;
  DETAIL_EXPOSURECOMPENSATOR_CHANNELS_BLOCKS =  4;
Type
  TCvdetail_WaveCorrectKind = (  WAVE_CORRECT_HORIZ =  0,  WAVE_CORRECT_VERT =  1,  WAVE_CORRECT_AUTO =  2  );
Const
  DETAIL_SEAMFINDER_NO =  0;
  DETAIL_SEAMFINDER_VORONOI_SEAM =  1;
  DETAIL_SEAMFINDER_DP_SEAM =  2;
Type
  TCvdetail_DpSeamFinder_CostFunction = (  DPSEAMFINDER_COLOR =  0,  DPSEAMFINDER_COLOR_GRAD =  1  );
  TCvdetail_GraphCutSeamFinderBase_CostType = (  GRAPHCUTSEAMFINDERBASE_COST_COLOR =  0,  GRAPHCUTSEAMFINDERBASE_COST_COLOR_GRAD =  1  );
Const
  DETAIL_TIMELAPSER_AS_IS =  0;
  DETAIL_TIMELAPSER_CROP =  1;
  OPTFLOW_USE_INITIAL_FLOW =  4;
  OPTFLOW_LK_GET_MIN_EIGENVALS =  8;
  OPTFLOW_FARNEBACK_GAUSSIAN =  256;
  MOTION_TRANSLATION =  0;
  MOTION_EUCLIDEAN =  1;
  MOTION_AFFINE =  2;
  MOTION_HOMOGRAPHY =  3;
  DISOPTICALFLOW_PRESET_ULTRAFAST =  0;
  DISOPTICALFLOW_PRESET_FAST =  1;
  DISOPTICALFLOW_PRESET_MEDIUM =  2;
Type
  TCvVideoCaptureAPIs = (  CAP_ANY =  0,  CAP_VFW =  200,  CAP_V4L =  200,
          CAP_V4L2 =  CAP_V4L,  CAP_FIREWIRE =  300,  CAP_FIREWARE =  CAP_FIREWIRE,
          CAP_IEEE1394 =  CAP_FIREWIRE,  CAP_DC1394 =  CAP_FIREWIRE,  CAP_CMU1394 =  CAP_FIREWIRE,
          CAP_QT =  500,  CAP_UNICAP =  600,  CAP_DSHOW =  700,
          CAP_PVAPI =  800,  CAP_OPENNI =  900,  CAP_OPENNI_ASUS =  910,
          CAP_ANDROID =  1000,  CAP_XIAPI =  1100,  CAP_AVFOUNDATION =  1200,
          CAP_GIGANETIX =  1300,  CAP_MSMF =  1400,  CAP_WINRT =  1410,
          CAP_INTELPERC =  1500,  CAP_REALSENSE =  1500,  CAP_OPENNI2 =  1600,
          CAP_OPENNI2_ASUS =  1610,  CAP_OPENNI2_ASTRA =  1620,  CAP_GPHOTO2 =  1700,
          CAP_GSTREAMER =  1800,  CAP_FFMPEG =  1900,  CAP_IMAGES =  2000,
          CAP_ARAVIS =  2100,  CAP_OPENCV_MJPEG =  2200,  CAP_INTEL_MFX =  2300,
          CAP_XINE =  2400,  CAP_UEYE =  2500  );
  TCvVideoCaptureProperties = (  CAP_PROP_POS_MSEC =  0,  CAP_PROP_POS_FRAMES =  1,  CAP_PROP_POS_AVI_RATIO =  2,
          CAP_PROP_FRAME_WIDTH =  3,  CAP_PROP_FRAME_HEIGHT =  4,  CAP_PROP_FPS =  5,
          CAP_PROP_FOURCC =  6,  CAP_PROP_FRAME_COUNT =  7,  CAP_PROP_FORMAT =  8,
          CAP_PROP_MODE =  9,  CAP_PROP_BRIGHTNESS =  10,  CAP_PROP_CONTRAST =  11,
          CAP_PROP_SATURATION =  12,  CAP_PROP_HUE =  13,  CAP_PROP_GAIN =  14,
          CAP_PROP_EXPOSURE =  15,  CAP_PROP_CONVERT_RGB =  16,  CAP_PROP_WHITE_BALANCE_BLUE_U =  17,
          CAP_PROP_RECTIFICATION =  18,  CAP_PROP_MONOCHROME =  19,  CAP_PROP_SHARPNESS =  20,
          CAP_PROP_AUTO_EXPOSURE =  21,  CAP_PROP_GAMMA =  22,  CAP_PROP_TEMPERATURE =  23,
          CAP_PROP_TRIGGER =  24,  CAP_PROP_TRIGGER_DELAY =  25,  CAP_PROP_WHITE_BALANCE_RED_V =  26,
          CAP_PROP_ZOOM =  27,  CAP_PROP_FOCUS =  28,  CAP_PROP_GUID =  29,
          CAP_PROP_ISO_SPEED =  30,  CAP_PROP_BACKLIGHT =  32,  CAP_PROP_PAN =  33,
          CAP_PROP_TILT =  34,  CAP_PROP_ROLL =  35,  CAP_PROP_IRIS =  36,
          CAP_PROP_SETTINGS =  37,  CAP_PROP_BUFFERSIZE =  38,  CAP_PROP_AUTOFOCUS =  39,
          CAP_PROP_SAR_NUM =  40,  CAP_PROP_SAR_DEN =  41,  CAP_PROP_BACKEND =  42,
          CAP_PROP_CHANNEL =  43,  CAP_PROP_AUTO_WB =  44,  CAP_PROP_WB_TEMPERATURE =  45,
          CAP_PROP_CODEC_PIXEL_FORMAT =  46,  CAP_PROP_BITRATE =  47,  CAP_PROP_ORIENTATION_META =  48,
          CAP_PROP_ORIENTATION_AUTO =  49,  CAP_PROP_HW_ACCELERATION =  50,  CAP_PROP_HW_DEVICE =  51,
          CAP_PROP_HW_ACCELERATION_USE_OPENCL =  52,  CAP_PROP_OPEN_TIMEOUT_MSEC =  53,  CAP_PROP_READ_TIMEOUT_MSEC =  54,
          CAP_PROP_STREAM_OPEN_TIME_USEC =  55,  CAP_PROP_VIDEO_TOTAL_CHANNELS =  56,  CAP_PROP_VIDEO_STREAM =  57,
          CAP_PROP_AUDIO_STREAM =  58,  CAP_PROP_AUDIO_POS =  59,  CAP_PROP_AUDIO_SHIFT_NSEC =  60,
          CAP_PROP_AUDIO_DATA_DEPTH =  61,  CAP_PROP_AUDIO_SAMPLES_PER_SECOND =  62,  CAP_PROP_AUDIO_BASE_INDEX =  63,
          CAP_PROP_AUDIO_TOTAL_CHANNELS =  64,  CAP_PROP_AUDIO_TOTAL_STREAMS =  65,  CAP_PROP_AUDIO_SYNCHRONIZE =  66,
          CAP_PROP_LRF_HAS_KEY_FRAME =  67,  CAP_PROP_CODEC_EXTRADATA_INDEX =  68  );
  TCvVideoWriterProperties = (  VIDEOWRITER_PROP_QUALITY =  1,  VIDEOWRITER_PROP_FRAMEBYTES =  2,  VIDEOWRITER_PROP_NSTRIPES =  3,
          VIDEOWRITER_PROP_IS_COLOR =  4,  VIDEOWRITER_PROP_DEPTH =  5,  VIDEOWRITER_PROP_HW_ACCELERATION =  6,
          VIDEOWRITER_PROP_HW_DEVICE =  7,  VIDEOWRITER_PROP_HW_ACCELERATION_USE_OPENCL =  8  );
  TCvVideoAccelerationType = (  VIDEO_ACCELERATION_NONE =  0,  VIDEO_ACCELERATION_ANY =  1,  VIDEO_ACCELERATION_D3D11 =  2,
          VIDEO_ACCELERATION_VAAPI =  3,  VIDEO_ACCELERATION_MFX =  4  );
Const
  CAP_PROP_DC1394_OFF =  -4;
  CAP_PROP_DC1394_MODE_MANUAL =  -3;
  CAP_PROP_DC1394_MODE_AUTO =  -2;
  CAP_PROP_DC1394_MODE_ONE_PUSH_AUTO =  -1;
  CAP_PROP_DC1394_MAX =  31;
  CAP_OPENNI_DEPTH_GENERATOR =  1  shl  31;
  CAP_OPENNI_IMAGE_GENERATOR =  1  shl  30;
  CAP_OPENNI_IR_GENERATOR =  1  shl  29;
  CAP_OPENNI_GENERATORS_MASK =  CAP_OPENNI_DEPTH_GENERATOR + CAP_OPENNI_IMAGE_GENERATOR + CAP_OPENNI_IR_GENERATOR;
  CAP_PROP_OPENNI_OUTPUT_MODE =  100;
  CAP_PROP_OPENNI_FRAME_MAX_DEPTH =  101;
  CAP_PROP_OPENNI_BASELINE =  102;
  CAP_PROP_OPENNI_FOCAL_LENGTH =  103;
  CAP_PROP_OPENNI_REGISTRATION =  104;
  CAP_PROP_OPENNI_REGISTRATION_ON =  CAP_PROP_OPENNI_REGISTRATION;
  CAP_PROP_OPENNI_APPROX_FRAME_SYNC =  105;
  CAP_PROP_OPENNI_MAX_BUFFER_SIZE =  106;
  CAP_PROP_OPENNI_CIRCLE_BUFFER =  107;
  CAP_PROP_OPENNI_MAX_TIME_DURATION =  108;
  CAP_PROP_OPENNI_GENERATOR_PRESENT =  109;
  CAP_PROP_OPENNI2_SYNC =  110;
  CAP_PROP_OPENNI2_MIRROR =  111;
  CAP_OPENNI_IMAGE_GENERATOR_PRESENT =  CAP_OPENNI_IMAGE_GENERATOR + CAP_PROP_OPENNI_GENERATOR_PRESENT;
  CAP_OPENNI_IMAGE_GENERATOR_OUTPUT_MODE =  CAP_OPENNI_IMAGE_GENERATOR + CAP_PROP_OPENNI_OUTPUT_MODE;
  CAP_OPENNI_DEPTH_GENERATOR_PRESENT =  CAP_OPENNI_DEPTH_GENERATOR + CAP_PROP_OPENNI_GENERATOR_PRESENT;
  CAP_OPENNI_DEPTH_GENERATOR_BASELINE =  CAP_OPENNI_DEPTH_GENERATOR + CAP_PROP_OPENNI_BASELINE;
  CAP_OPENNI_DEPTH_GENERATOR_FOCAL_LENGTH =  CAP_OPENNI_DEPTH_GENERATOR + CAP_PROP_OPENNI_FOCAL_LENGTH;
  CAP_OPENNI_DEPTH_GENERATOR_REGISTRATION =  CAP_OPENNI_DEPTH_GENERATOR + CAP_PROP_OPENNI_REGISTRATION;
  CAP_OPENNI_DEPTH_GENERATOR_REGISTRATION_ON =  CAP_OPENNI_DEPTH_GENERATOR_REGISTRATION;
  CAP_OPENNI_IR_GENERATOR_PRESENT =  CAP_OPENNI_IR_GENERATOR + CAP_PROP_OPENNI_GENERATOR_PRESENT;
  CAP_OPENNI_DEPTH_MAP =  0;
  CAP_OPENNI_POINT_CLOUD_MAP =  1;
  CAP_OPENNI_DISPARITY_MAP =  2;
  CAP_OPENNI_DISPARITY_MAP_32F =  3;
  CAP_OPENNI_VALID_DEPTH_MASK =  4;
  CAP_OPENNI_BGR_IMAGE =  5;
  CAP_OPENNI_GRAY_IMAGE =  6;
  CAP_OPENNI_IR_IMAGE =  7;
  CAP_OPENNI_VGA_30HZ =  0;
  CAP_OPENNI_SXGA_15HZ =  1;
  CAP_OPENNI_SXGA_30HZ =  2;
  CAP_OPENNI_QVGA_30HZ =  3;
  CAP_OPENNI_QVGA_60HZ =  4;
  CAP_PROP_GSTREAMER_QUEUE_LENGTH =  200;
  CAP_PROP_PVAPI_MULTICASTIP =  300;
  CAP_PROP_PVAPI_FRAMESTARTTRIGGERMODE =  301;
  CAP_PROP_PVAPI_DECIMATIONHORIZONTAL =  302;
  CAP_PROP_PVAPI_DECIMATIONVERTICAL =  303;
  CAP_PROP_PVAPI_BINNINGX =  304;
  CAP_PROP_PVAPI_BINNINGY =  305;
  CAP_PROP_PVAPI_PIXELFORMAT =  306;
  CAP_PVAPI_FSTRIGMODE_FREERUN =  0;
  CAP_PVAPI_FSTRIGMODE_SYNCIN1 =  1;
  CAP_PVAPI_FSTRIGMODE_SYNCIN2 =  2;
  CAP_PVAPI_FSTRIGMODE_FIXEDRATE =  3;
  CAP_PVAPI_FSTRIGMODE_SOFTWARE =  4;
  CAP_PVAPI_DECIMATION_OFF =  1;
  CAP_PVAPI_DECIMATION_2OUTOF4 =  2;
  CAP_PVAPI_DECIMATION_2OUTOF8 =  4;
  CAP_PVAPI_DECIMATION_2OUTOF16 =  8;
  CAP_PVAPI_PIXELFORMAT_MONO8 =  1;
  CAP_PVAPI_PIXELFORMAT_MONO16 =  2;
  CAP_PVAPI_PIXELFORMAT_BAYER8 =  3;
  CAP_PVAPI_PIXELFORMAT_BAYER16 =  4;
  CAP_PVAPI_PIXELFORMAT_RGB24 =  5;
  CAP_PVAPI_PIXELFORMAT_BGR24 =  6;
  CAP_PVAPI_PIXELFORMAT_RGBA32 =  7;
  CAP_PVAPI_PIXELFORMAT_BGRA32 =  8;
  CAP_PROP_XI_DOWNSAMPLING =  400;
  CAP_PROP_XI_DATA_FORMAT =  401;
  CAP_PROP_XI_OFFSET_X =  402;
  CAP_PROP_XI_OFFSET_Y =  403;
  CAP_PROP_XI_TRG_SOURCE =  404;
  CAP_PROP_XI_TRG_SOFTWARE =  405;
  CAP_PROP_XI_GPI_SELECTOR =  406;
  CAP_PROP_XI_GPI_MODE =  407;
  CAP_PROP_XI_GPI_LEVEL =  408;
  CAP_PROP_XI_GPO_SELECTOR =  409;
  CAP_PROP_XI_GPO_MODE =  410;
  CAP_PROP_XI_LED_SELECTOR =  411;
  CAP_PROP_XI_LED_MODE =  412;
  CAP_PROP_XI_MANUAL_WB =  413;
  CAP_PROP_XI_AUTO_WB =  414;
  CAP_PROP_XI_AEAG =  415;
  CAP_PROP_XI_EXP_PRIORITY =  416;
  CAP_PROP_XI_AE_MAX_LIMIT =  417;
  CAP_PROP_XI_AG_MAX_LIMIT =  418;
  CAP_PROP_XI_AEAG_LEVEL =  419;
  CAP_PROP_XI_TIMEOUT =  420;
  CAP_PROP_XI_EXPOSURE =  421;
  CAP_PROP_XI_EXPOSURE_BURST_COUNT =  422;
  CAP_PROP_XI_GAIN_SELECTOR =  423;
  CAP_PROP_XI_GAIN =  424;
  CAP_PROP_XI_DOWNSAMPLING_TYPE =  426;
  CAP_PROP_XI_BINNING_SELECTOR =  427;
  CAP_PROP_XI_BINNING_VERTICAL =  428;
  CAP_PROP_XI_BINNING_HORIZONTAL =  429;
  CAP_PROP_XI_BINNING_PATTERN =  430;
  CAP_PROP_XI_DECIMATION_SELECTOR =  431;
  CAP_PROP_XI_DECIMATION_VERTICAL =  432;
  CAP_PROP_XI_DECIMATION_HORIZONTAL =  433;
  CAP_PROP_XI_DECIMATION_PATTERN =  434;
  CAP_PROP_XI_TEST_PATTERN_GENERATOR_SELECTOR =  587;
  CAP_PROP_XI_TEST_PATTERN =  588;
  CAP_PROP_XI_IMAGE_DATA_FORMAT =  435;
  CAP_PROP_XI_SHUTTER_TYPE =  436;
  CAP_PROP_XI_SENSOR_TAPS =  437;
  CAP_PROP_XI_AEAG_ROI_OFFSET_X =  439;
  CAP_PROP_XI_AEAG_ROI_OFFSET_Y =  440;
  CAP_PROP_XI_AEAG_ROI_WIDTH =  441;
  CAP_PROP_XI_AEAG_ROI_HEIGHT =  442;
  CAP_PROP_XI_BPC =  445;
  CAP_PROP_XI_WB_KR =  448;
  CAP_PROP_XI_WB_KG =  449;
  CAP_PROP_XI_WB_KB =  450;
  CAP_PROP_XI_WIDTH =  451;
  CAP_PROP_XI_HEIGHT =  452;
  CAP_PROP_XI_REGION_SELECTOR =  589;
  CAP_PROP_XI_REGION_MODE =  595;
  CAP_PROP_XI_LIMIT_BANDWIDTH =  459;
  CAP_PROP_XI_SENSOR_DATA_BIT_DEPTH =  460;
  CAP_PROP_XI_OUTPUT_DATA_BIT_DEPTH =  461;
  CAP_PROP_XI_IMAGE_DATA_BIT_DEPTH =  462;
  CAP_PROP_XI_OUTPUT_DATA_PACKING =  463;
  CAP_PROP_XI_OUTPUT_DATA_PACKING_TYPE =  464;
  CAP_PROP_XI_IS_COOLED =  465;
  CAP_PROP_XI_COOLING =  466;
  CAP_PROP_XI_TARGET_TEMP =  467;
  CAP_PROP_XI_CHIP_TEMP =  468;
  CAP_PROP_XI_HOUS_TEMP =  469;
  CAP_PROP_XI_HOUS_BACK_SIDE_TEMP =  590;
  CAP_PROP_XI_SENSOR_BOARD_TEMP =  596;
  CAP_PROP_XI_CMS =  470;
  CAP_PROP_XI_APPLY_CMS =  471;
  CAP_PROP_XI_IMAGE_IS_COLOR =  474;
  CAP_PROP_XI_COLOR_FILTER_ARRAY =  475;
  CAP_PROP_XI_GAMMAY =  476;
  CAP_PROP_XI_GAMMAC =  477;
  CAP_PROP_XI_SHARPNESS =  478;
  CAP_PROP_XI_CC_MATRIX_00 =  479;
  CAP_PROP_XI_CC_MATRIX_01 =  480;
  CAP_PROP_XI_CC_MATRIX_02 =  481;
  CAP_PROP_XI_CC_MATRIX_03 =  482;
  CAP_PROP_XI_CC_MATRIX_10 =  483;
  CAP_PROP_XI_CC_MATRIX_11 =  484;
  CAP_PROP_XI_CC_MATRIX_12 =  485;
  CAP_PROP_XI_CC_MATRIX_13 =  486;
  CAP_PROP_XI_CC_MATRIX_20 =  487;
  CAP_PROP_XI_CC_MATRIX_21 =  488;
  CAP_PROP_XI_CC_MATRIX_22 =  489;
  CAP_PROP_XI_CC_MATRIX_23 =  490;
  CAP_PROP_XI_CC_MATRIX_30 =  491;
  CAP_PROP_XI_CC_MATRIX_31 =  492;
  CAP_PROP_XI_CC_MATRIX_32 =  493;
  CAP_PROP_XI_CC_MATRIX_33 =  494;
  CAP_PROP_XI_DEFAULT_CC_MATRIX =  495;
  CAP_PROP_XI_TRG_SELECTOR =  498;
  CAP_PROP_XI_ACQ_FRAME_BURST_COUNT =  499;
  CAP_PROP_XI_DEBOUNCE_EN =  507;
  CAP_PROP_XI_DEBOUNCE_T0 =  508;
  CAP_PROP_XI_DEBOUNCE_T1 =  509;
  CAP_PROP_XI_DEBOUNCE_POL =  510;
  CAP_PROP_XI_LENS_MODE =  511;
  CAP_PROP_XI_LENS_APERTURE_VALUE =  512;
  CAP_PROP_XI_LENS_FOCUS_MOVEMENT_VALUE =  513;
  CAP_PROP_XI_LENS_FOCUS_MOVE =  514;
  CAP_PROP_XI_LENS_FOCUS_DISTANCE =  515;
  CAP_PROP_XI_LENS_FOCAL_LENGTH =  516;
  CAP_PROP_XI_LENS_FEATURE_SELECTOR =  517;
  CAP_PROP_XI_LENS_FEATURE =  518;
  CAP_PROP_XI_DEVICE_MODEL_ID =  521;
  CAP_PROP_XI_DEVICE_SN =  522;
  CAP_PROP_XI_IMAGE_DATA_FORMAT_RGB32_ALPHA =  529;
  CAP_PROP_XI_IMAGE_PAYLOAD_SIZE =  530;
  CAP_PROP_XI_TRANSPORT_PIXEL_FORMAT =  531;
  CAP_PROP_XI_SENSOR_CLOCK_FREQ_HZ =  532;
  CAP_PROP_XI_SENSOR_CLOCK_FREQ_INDEX =  533;
  CAP_PROP_XI_SENSOR_OUTPUT_CHANNEL_COUNT =  534;
  CAP_PROP_XI_FRAMERATE =  535;
  CAP_PROP_XI_COUNTER_SELECTOR =  536;
  CAP_PROP_XI_COUNTER_VALUE =  537;
  CAP_PROP_XI_ACQ_TIMING_MODE =  538;
  CAP_PROP_XI_AVAILABLE_BANDWIDTH =  539;
  CAP_PROP_XI_BUFFER_POLICY =  540;
  CAP_PROP_XI_LUT_EN =  541;
  CAP_PROP_XI_LUT_INDEX =  542;
  CAP_PROP_XI_LUT_VALUE =  543;
  CAP_PROP_XI_TRG_DELAY =  544;
  CAP_PROP_XI_TS_RST_MODE =  545;
  CAP_PROP_XI_TS_RST_SOURCE =  546;
  CAP_PROP_XI_IS_DEVICE_EXIST =  547;
  CAP_PROP_XI_ACQ_BUFFER_SIZE =  548;
  CAP_PROP_XI_ACQ_BUFFER_SIZE_UNIT =  549;
  CAP_PROP_XI_ACQ_TRANSPORT_BUFFER_SIZE =  550;
  CAP_PROP_XI_BUFFERS_QUEUE_SIZE =  551;
  CAP_PROP_XI_ACQ_TRANSPORT_BUFFER_COMMIT =  552;
  CAP_PROP_XI_RECENT_FRAME =  553;
  CAP_PROP_XI_DEVICE_RESET =  554;
  CAP_PROP_XI_COLUMN_FPN_CORRECTION =  555;
  CAP_PROP_XI_ROW_FPN_CORRECTION =  591;
  CAP_PROP_XI_SENSOR_MODE =  558;
  CAP_PROP_XI_HDR =  559;
  CAP_PROP_XI_HDR_KNEEPOINT_COUNT =  560;
  CAP_PROP_XI_HDR_T1 =  561;
  CAP_PROP_XI_HDR_T2 =  562;
  CAP_PROP_XI_KNEEPOINT1 =  563;
  CAP_PROP_XI_KNEEPOINT2 =  564;
  CAP_PROP_XI_IMAGE_BLACK_LEVEL =  565;
  CAP_PROP_XI_HW_REVISION =  571;
  CAP_PROP_XI_DEBUG_LEVEL =  572;
  CAP_PROP_XI_AUTO_BANDWIDTH_CALCULATION =  573;
  CAP_PROP_XI_FFS_FILE_ID =  594;
  CAP_PROP_XI_FFS_FILE_SIZE =  580;
  CAP_PROP_XI_FREE_FFS_SIZE =  581;
  CAP_PROP_XI_USED_FFS_SIZE =  582;
  CAP_PROP_XI_FFS_ACCESS_KEY =  583;
  CAP_PROP_XI_SENSOR_FEATURE_SELECTOR =  585;
  CAP_PROP_XI_SENSOR_FEATURE_VALUE =  586;
  CAP_PROP_ARAVIS_AUTOTRIGGER =  600;
  CAP_PROP_IOS_DEVICE_FOCUS =  9001;
  CAP_PROP_IOS_DEVICE_EXPOSURE =  9002;
  CAP_PROP_IOS_DEVICE_FLASH =  9003;
  CAP_PROP_IOS_DEVICE_WHITEBALANCE =  9004;
  CAP_PROP_IOS_DEVICE_TORCH =  9005;
  CAP_PROP_GIGA_FRAME_OFFSET_X =  10001;
  CAP_PROP_GIGA_FRAME_OFFSET_Y =  10002;
  CAP_PROP_GIGA_FRAME_WIDTH_MAX =  10003;
  CAP_PROP_GIGA_FRAME_HEIGH_MAX =  10004;
  CAP_PROP_GIGA_FRAME_SENS_WIDTH =  10005;
  CAP_PROP_GIGA_FRAME_SENS_HEIGH =  10006;
  CAP_PROP_INTELPERC_PROFILE_COUNT =  11001;
  CAP_PROP_INTELPERC_PROFILE_IDX =  11002;
  CAP_PROP_INTELPERC_DEPTH_LOW_CONFIDENCE_VALUE =  11003;
  CAP_PROP_INTELPERC_DEPTH_SATURATION_VALUE =  11004;
  CAP_PROP_INTELPERC_DEPTH_CONFIDENCE_THRESHOLD =  11005;
  CAP_PROP_INTELPERC_DEPTH_FOCAL_LENGTH_HORZ =  11006;
  CAP_PROP_INTELPERC_DEPTH_FOCAL_LENGTH_VERT =  11007;
  CAP_INTELPERC_DEPTH_GENERATOR =  1  shl  29;
  CAP_INTELPERC_IMAGE_GENERATOR =  1  shl  28;
  CAP_INTELPERC_IR_GENERATOR =  1  shl  27;
  CAP_INTELPERC_GENERATORS_MASK =  CAP_INTELPERC_DEPTH_GENERATOR + CAP_INTELPERC_IMAGE_GENERATOR + CAP_INTELPERC_IR_GENERATOR;
  CAP_INTELPERC_DEPTH_MAP =  0;
  CAP_INTELPERC_UVDEPTH_MAP =  1;
  CAP_INTELPERC_IR_MAP =  2;
  CAP_INTELPERC_IMAGE =  3;
  CAP_PROP_GPHOTO2_PREVIEW =  17001;
  CAP_PROP_GPHOTO2_WIDGET_ENUMERATE =  17002;
  CAP_PROP_GPHOTO2_RELOAD_CONFIG =  17003;
  CAP_PROP_GPHOTO2_RELOAD_ON_CHANGE =  17004;
  CAP_PROP_GPHOTO2_COLLECT_MSGS =  17005;
  CAP_PROP_GPHOTO2_FLUSH_MSGS =  17006;
  CAP_PROP_SPEED =  17007;
  CAP_PROP_APERTURE =  17008;
  CAP_PROP_EXPOSUREPROGRAM =  17009;
  CAP_PROP_VIEWFINDER =  17010;
  CAP_PROP_IMAGES_BASE =  18000;
  CAP_PROP_IMAGES_LAST =  19000;
