Function    pCvSizeCreate(): PCvSize_t; cdecl;
Procedure   pCvSizeDelete(const wrapper: PCvSize_t); cdecl;
Procedure   pCvSizeToStruct(const wrapper: PCvSize_t; const dest: PCvSizeS); cdecl;
Procedure   pCvSizeFromStruct(const wrapper: PCvSize_t; const src: PCvSizeS); cdecl;
Function    pCvRectCreate(): PCvRect_t; cdecl;
Procedure   pCvRectDelete(const wrapper: PCvRect_t); cdecl;
Procedure   pCvRectToStruct(const wrapper: PCvRect_t; const dest: PCvRectS); cdecl;
Procedure   pCvRectFromStruct(const wrapper: PCvRect_t; const src: PCvRectS); cdecl;
Function    pCvRangeCreate(): PCvRange_t; cdecl;
Procedure   pCvRangeDelete(const wrapper: PCvRange_t); cdecl;
Procedure   pCvRangeToStruct(const wrapper: PCvRange_t; const dest: PCvRangeS); cdecl;
Procedure   pCvRangeFromStruct(const wrapper: PCvRange_t; const src: PCvRangeS); cdecl;
Function    pCvCvSliceCreate(): PCvCvSlice_t; cdecl;
Procedure   pCvCvSliceDelete(const wrapper: PCvCvSlice_t); cdecl;
Procedure   pCvCvSliceToStruct(const wrapper: PCvCvSlice_t; const dest: PCvSliceS); cdecl;
Procedure   pCvCvSliceFromStruct(const wrapper: PCvCvSlice_t; const src: PCvSliceS); cdecl;
Function    pCvPointCreate(): PCvPoint_t; cdecl;
Procedure   pCvPointDelete(const wrapper: PCvPoint_t); cdecl;
Procedure   pCvPointToStruct(const wrapper: PCvPoint_t; const dest: PCvPointS); cdecl;
Procedure   pCvPointFromStruct(const wrapper: PCvPoint_t; const src: PCvPointS); cdecl;
Function    pCvPoint2fCreate(): PCvPoint2f_t; cdecl;
Procedure   pCvPoint2fDelete(const wrapper: PCvPoint2f_t); cdecl;
Procedure   pCvPoint2fToStruct(const wrapper: PCvPoint2f_t; const dest: PCvPoint2fS); cdecl;
Procedure   pCvPoint2fFromStruct(const wrapper: PCvPoint2f_t; const src: PCvPoint2fS); cdecl;
Function    pCvPoint2dCreate(): PCvPoint2d_t; cdecl;
Procedure   pCvPoint2dDelete(const wrapper: PCvPoint2d_t); cdecl;
Procedure   pCvPoint2dToStruct(const wrapper: PCvPoint2d_t; const dest: PCvPoint2dS); cdecl;
Procedure   pCvPoint2dFromStruct(const wrapper: PCvPoint2d_t; const src: PCvPoint2dS); cdecl;
Function    pCvVec2dCreate(): PCvVec2d_t; cdecl;
Procedure   pCvVec2dDelete(const wrapper: PCvVec2d_t); cdecl;
Procedure   pCvVec2dToStruct(const wrapper: PCvVec2d_t; const dest: PCvVec2dS); cdecl;
Procedure   pCvVec2dFromStruct(const wrapper: PCvVec2d_t; const src: PCvVec2dS); cdecl;
Function    pCvVec3dCreate(): PCvVec3d_t; cdecl;
Procedure   pCvVec3dDelete(const wrapper: PCvVec3d_t); cdecl;
Procedure   pCvVec3dToStruct(const wrapper: PCvVec3d_t; const dest: PCvVec3dS); cdecl;
Procedure   pCvVec3dFromStruct(const wrapper: PCvVec3d_t; const src: PCvVec3dS); cdecl;
Function    pCvVec3bCreate(): PCvVec3b_t; cdecl;
Procedure   pCvVec3bDelete(const wrapper: PCvVec3b_t); cdecl;
Procedure   pCvVec3bToStruct(const wrapper: PCvVec3b_t; const dest: PCvVec3bS); cdecl;
Procedure   pCvVec3bFromStruct(const wrapper: PCvVec3b_t; const src: PCvVec3bS); cdecl;
Function    pCvVec4fCreate(): PCvVec4f_t; cdecl;
Procedure   pCvVec4fDelete(const wrapper: PCvVec4f_t); cdecl;
Procedure   pCvVec4fToStruct(const wrapper: PCvVec4f_t; const dest: PCvVec4fS); cdecl;
Procedure   pCvVec4fFromStruct(const wrapper: PCvVec4f_t; const src: PCvVec4fS); cdecl;
Function    pCvVec6fCreate(): PCvVec6f_t; cdecl;
Procedure   pCvVec6fDelete(const wrapper: PCvVec6f_t); cdecl;
Procedure   pCvVec6fToStruct(const wrapper: PCvVec6f_t; const dest: PCvVec6fS); cdecl;
Procedure   pCvVec6fFromStruct(const wrapper: PCvVec6f_t; const src: PCvVec6fS); cdecl;
Function    pCvScalarCreate(): PCvScalar_t; cdecl;
Procedure   pCvScalarDelete(const wrapper: PCvScalar_t); cdecl;
Procedure   pCvScalarToStruct(const wrapper: PCvScalar_t; const dest: PCvScalarS); cdecl;
Procedure   pCvScalarFromStruct(const wrapper: PCvScalar_t; const src: PCvScalarS); cdecl;
Function    pCvRotatedRectCreate(): PCvRotatedRect_t; cdecl;
Procedure   pCvRotatedRectDelete(const wrapper: PCvRotatedRect_t); cdecl;
Procedure   pCvRotatedRectToStruct(const wrapper: PCvRotatedRect_t; const dest: PCvRotatedRectS); cdecl;
Procedure   pCvRotatedRectFromStruct(const wrapper: PCvRotatedRect_t; const src: PCvRotatedRectS); cdecl;
Function    pCvTermCriteriaCreate(): PCvTermCriteria_t; cdecl;
Procedure   pCvTermCriteriaDelete(const wrapper: PCvTermCriteria_t); cdecl;
Procedure   pCvTermCriteriaToStruct(const wrapper: PCvTermCriteria_t; const dest: PCvTermCriteriaS); cdecl;
Procedure   pCvTermCriteriaFromStruct(const wrapper: PCvTermCriteria_t; const src: PCvTermCriteriaS); cdecl;
Function    pCvCvTermCriteriaCreate(): PCvCvTermCriteria_t; cdecl;
Procedure   pCvCvTermCriteriaDelete(const wrapper: PCvCvTermCriteria_t); cdecl;
Procedure   pCvCvTermCriteriaToStruct(const wrapper: PCvCvTermCriteria_t; const dest: PCvTermCriteriaS); cdecl;
Procedure   pCvCvTermCriteriaFromStruct(const wrapper: PCvCvTermCriteria_t; const src: PCvTermCriteriaS); cdecl;
Function    pCvMomentsCreate(): PCvMoments_t; cdecl;
Procedure   pCvMomentsDelete(const wrapper: PCvMoments_t); cdecl;
Procedure   pCvMomentsToStruct(const wrapper: PCvMoments_t; const dest: PCvMomentsS); cdecl;
Procedure   pCvMomentsFromStruct(const wrapper: PCvMoments_t; const src: PCvMomentsS); cdecl;
Function    pCvIndexParamsCreate(): PCvIndexParams_t; cdecl;
Procedure   pCvIndexParamsDelete(const wrapper: PCvIndexParams_t); cdecl;
Function    pCvSearchParamsCreate(): PCvSearchParams_t; cdecl;
Procedure   pCvSearchParamsDelete(const wrapper: PCvSearchParams_t); cdecl;
Function    pCvLayerIdCreate(): PCvLayerId_t; cdecl;
Procedure   pCvLayerIdDelete(const wrapper: PCvLayerId_t); cdecl;
Function    pCvRNGCreate(): PCvRNG_t; cdecl;
Procedure   pCvRNGDelete(const wrapper: PCvRNG_t); cdecl;
Function    pCvSize2fCreate(): PCvSize2f_t; cdecl;
Procedure   pCvSize2fDelete(const wrapper: PCvSize2f_t); cdecl;
Procedure   pCvSize2fToStruct(const wrapper: PCvSize2f_t; const dest: PCvSize2fS); cdecl;
Procedure   pCvSize2fFromStruct(const wrapper: PCvSize2f_t; const src: PCvSize2fS); cdecl;
Function    pCvVec2iCreate(): PCvVec2i_t; cdecl;
Procedure   pCvVec2iDelete(const wrapper: PCvVec2i_t); cdecl;
Procedure   pCvVec2iToStruct(const wrapper: PCvVec2i_t; const dest: PCvVec2iS); cdecl;
Procedure   pCvVec2iFromStruct(const wrapper: PCvVec2i_t; const src: PCvVec2iS); cdecl;
Function    pCvVec3iCreate(): PCvVec3i_t; cdecl;
Procedure   pCvVec3iDelete(const wrapper: PCvVec3i_t); cdecl;
Procedure   pCvVec3iToStruct(const wrapper: PCvVec3i_t; const dest: PCvVec3iS); cdecl;
Procedure   pCvVec3iFromStruct(const wrapper: PCvVec3i_t; const src: PCvVec3iS); cdecl;
Function    pCvRect2dCreate(): PCvRect2d_t; cdecl;
Procedure   pCvRect2dDelete(const wrapper: PCvRect2d_t); cdecl;
Procedure   pCvRect2dToStruct(const wrapper: PCvRect2d_t; const dest: PCvRect2dS); cdecl;
Procedure   pCvRect2dFromStruct(const wrapper: PCvRect2d_t; const src: PCvRect2dS); cdecl;
Function    pCvMatShapeCreate(const n: Integer): PCvMatShape; cdecl;
Procedure   pCvMatShapeDelete(const wrapper: PCvMatShape); cdecl;
Function    pCvMatShapeLength(const wrapper: PCvMatShape): Integer; cdecl;
Function    pCvMatShapeGet(const wrapper: PCvMatShape; const index: Integer): Integer; cdecl;
Function    pCvMatShapeSet(const wrapper: PCvMatShape; const index: Integer; const val: Integer): Integer; cdecl;
Function    pCvVectordetail_CameraParamsCreate(const n: Integer): PCvvector_CameraParams; cdecl;
Procedure   pCvVectordetail_CameraParamsDelete(const wrapper: PCvvector_CameraParams); cdecl;
Function    pCvVectordetail_CameraParamsLength(const wrapper: PCvvector_CameraParams): Integer; cdecl;
Function    pCvVectordetail_CameraParamsGet(const wrapper: PCvvector_CameraParams; const index: Integer): PCvdetail_CameraParams_t; cdecl;
Function    pCvVectordetail_CameraParamsSet(const wrapper: PCvvector_CameraParams; const index: Integer; const val: PCvdetail_CameraParams_t): PCvdetail_CameraParams_t; cdecl;
Function    pCvVectorDMatchCreate(const n: Integer): PCvvector_DMatch; cdecl;
Procedure   pCvVectorDMatchDelete(const wrapper: PCvvector_DMatch); cdecl;
Function    pCvVectorDMatchLength(const wrapper: PCvvector_DMatch): Integer; cdecl;
Function    pCvVectorDMatchGet(const wrapper: PCvvector_DMatch; const index: Integer): PCvDMatch_t; cdecl;
Function    pCvVectorDMatchSet(const wrapper: PCvvector_DMatch; const index: Integer; const val: PCvDMatch_t): PCvDMatch_t; cdecl;
Function    pCvVectordetail_ImageFeaturesCreate(const n: Integer): PCvvector_ImageFeatures; cdecl;
Procedure   pCvVectordetail_ImageFeaturesDelete(const wrapper: PCvvector_ImageFeatures); cdecl;
Function    pCvVectordetail_ImageFeaturesLength(const wrapper: PCvvector_ImageFeatures): Integer; cdecl;
Function    pCvVectordetail_ImageFeaturesGet(const wrapper: PCvvector_ImageFeatures; const index: Integer): PCvdetail_ImageFeatures_t; cdecl;
Function    pCvVectordetail_ImageFeaturesSet(const wrapper: PCvvector_ImageFeatures; const index: Integer; const val: PCvdetail_ImageFeatures_t): PCvdetail_ImageFeatures_t; cdecl;
Function    pCvVectorKeyPointCreate(const n: Integer): PCvvector_KeyPoint; cdecl;
Procedure   pCvVectorKeyPointDelete(const wrapper: PCvvector_KeyPoint); cdecl;
Function    pCvVectorKeyPointLength(const wrapper: PCvvector_KeyPoint): Integer; cdecl;
Function    pCvVectorKeyPointGet(const wrapper: PCvvector_KeyPoint; const index: Integer): PCvKeyPoint_t; cdecl;
Function    pCvVectorKeyPointSet(const wrapper: PCvvector_KeyPoint; const index: Integer; const val: PCvKeyPoint_t): PCvKeyPoint_t; cdecl;
Function    pCvVectorMatCreate(const n: Integer): PCvvector_Mat; cdecl;
Procedure   pCvVectorMatDelete(const wrapper: PCvvector_Mat); cdecl;
Function    pCvVectorMatLength(const wrapper: PCvvector_Mat): Integer; cdecl;
Function    pCvVectorMatGet(const wrapper: PCvvector_Mat; const index: Integer): PCvMat_t; cdecl;
Function    pCvVectorMatSet(const wrapper: PCvvector_Mat; const index: Integer; const val: PCvMat_t): PCvMat_t; cdecl;
Function    pCvVectorMatShapeCreate(const n: Integer): PCvvector_MatShape; cdecl;
Procedure   pCvVectorMatShapeDelete(const wrapper: PCvvector_MatShape); cdecl;
Function    pCvVectorMatShapeLength(const wrapper: PCvvector_MatShape): Integer; cdecl;
Function    pCvVectorMatShapeGet(const wrapper: PCvvector_MatShape; const index: Integer): PCvvector_int; cdecl;
Function    pCvVectorMatShapeSet(const wrapper: PCvvector_MatShape; const index: Integer; const val: PCvvector_int): PCvvector_int; cdecl;
Function    pCvVectordetail_MatchesInfoCreate(const n: Integer): PCvvector_MatchesInfo; cdecl;
Procedure   pCvVectordetail_MatchesInfoDelete(const wrapper: PCvvector_MatchesInfo); cdecl;
Function    pCvVectordetail_MatchesInfoLength(const wrapper: PCvvector_MatchesInfo): Integer; cdecl;
Function    pCvVectordetail_MatchesInfoGet(const wrapper: PCvvector_MatchesInfo; const index: Integer): PCvdetail_MatchesInfo_t; cdecl;
Function    pCvVectordetail_MatchesInfoSet(const wrapper: PCvvector_MatchesInfo; const index: Integer; const val: PCvdetail_MatchesInfo_t): PCvdetail_MatchesInfo_t; cdecl;
Function    pCvVectorPointCreate(const n: Integer): PCvvector_Point; cdecl;
Procedure   pCvVectorPointDelete(const wrapper: PCvvector_Point); cdecl;
Function    pCvVectorPointLength(const wrapper: PCvvector_Point): Integer; cdecl;
Function    pCvVectorPointGet(const wrapper: PCvvector_Point; const index: Integer): PCvPoint_t; cdecl;
Function    pCvVectorPointSet(const wrapper: PCvvector_Point; const index: Integer; const val: PCvPoint_t): PCvPoint_t; cdecl;
Procedure   pCvVectorPointToArray(const wrapper: PCvvector_Point; outvalues: PCvPointS); cdecl;
Procedure   pCvVectorPointFromArray(const wrapper: PCvvector_Point; inpvalues: PCvPointS); cdecl;
Function    pCvVectorPoint2fCreate(const n: Integer): PCvvector_Point2f; cdecl;
Procedure   pCvVectorPoint2fDelete(const wrapper: PCvvector_Point2f); cdecl;
Function    pCvVectorPoint2fLength(const wrapper: PCvvector_Point2f): Integer; cdecl;
Function    pCvVectorPoint2fGet(const wrapper: PCvvector_Point2f; const index: Integer): PCvPoint2f_t; cdecl;
Function    pCvVectorPoint2fSet(const wrapper: PCvvector_Point2f; const index: Integer; const val: PCvPoint2f_t): PCvPoint2f_t; cdecl;
Procedure   pCvVectorPoint2fToArray(const wrapper: PCvvector_Point2f; outvalues: PCvPoint2fS); cdecl;
Procedure   pCvVectorPoint2fFromArray(const wrapper: PCvvector_Point2f; inpvalues: PCvPoint2fS); cdecl;
Function    pCvVectorRangeCreate(const n: Integer): PCvvector_Range; cdecl;
Procedure   pCvVectorRangeDelete(const wrapper: PCvvector_Range); cdecl;
Function    pCvVectorRangeLength(const wrapper: PCvvector_Range): Integer; cdecl;
Function    pCvVectorRangeGet(const wrapper: PCvvector_Range; const index: Integer): PCvRange_t; cdecl;
Function    pCvVectorRangeSet(const wrapper: PCvvector_Range; const index: Integer; const val: PCvRange_t): PCvRange_t; cdecl;
Procedure   pCvVectorRangeToArray(const wrapper: PCvvector_Range; outvalues: PCvRangeS); cdecl;
Procedure   pCvVectorRangeFromArray(const wrapper: PCvvector_Range; inpvalues: PCvRangeS); cdecl;
Function    pCvVectorRectCreate(const n: Integer): PCvvector_Rect; cdecl;
Procedure   pCvVectorRectDelete(const wrapper: PCvvector_Rect); cdecl;
Function    pCvVectorRectLength(const wrapper: PCvvector_Rect): Integer; cdecl;
Function    pCvVectorRectGet(const wrapper: PCvvector_Rect; const index: Integer): PCvRect_t; cdecl;
Function    pCvVectorRectSet(const wrapper: PCvvector_Rect; const index: Integer; const val: PCvRect_t): PCvRect_t; cdecl;
Procedure   pCvVectorRectToArray(const wrapper: PCvvector_Rect; outvalues: PCvRectS); cdecl;
Procedure   pCvVectorRectFromArray(const wrapper: PCvvector_Rect; inpvalues: PCvRectS); cdecl;
Function    pCvVectorRect2dCreate(const n: Integer): PCvvector_Rect2d; cdecl;
Procedure   pCvVectorRect2dDelete(const wrapper: PCvvector_Rect2d); cdecl;
Function    pCvVectorRect2dLength(const wrapper: PCvvector_Rect2d): Integer; cdecl;
Function    pCvVectorRect2dGet(const wrapper: PCvvector_Rect2d; const index: Integer): PCvRect2d_t; cdecl;
Function    pCvVectorRect2dSet(const wrapper: PCvvector_Rect2d; const index: Integer; const val: PCvRect2d_t): PCvRect2d_t; cdecl;
Procedure   pCvVectorRect2dToArray(const wrapper: PCvvector_Rect2d; outvalues: PCvRect2dS); cdecl;
Procedure   pCvVectorRect2dFromArray(const wrapper: PCvvector_Rect2d; inpvalues: PCvRect2dS); cdecl;
Function    pCvVectorRotatedRectCreate(const n: Integer): PCvvector_RotatedRect; cdecl;
Procedure   pCvVectorRotatedRectDelete(const wrapper: PCvvector_RotatedRect); cdecl;
Function    pCvVectorRotatedRectLength(const wrapper: PCvvector_RotatedRect): Integer; cdecl;
Function    pCvVectorRotatedRectGet(const wrapper: PCvvector_RotatedRect; const index: Integer): PCvRotatedRect_t; cdecl;
Function    pCvVectorRotatedRectSet(const wrapper: PCvvector_RotatedRect; const index: Integer; const val: PCvRotatedRect_t): PCvRotatedRect_t; cdecl;
Procedure   pCvVectorRotatedRectToArray(const wrapper: PCvvector_RotatedRect; outvalues: PCvRotatedRectS); cdecl;
Procedure   pCvVectorRotatedRectFromArray(const wrapper: PCvvector_RotatedRect; inpvalues: PCvRotatedRectS); cdecl;
Function    pCvVectorSizeCreate(const n: Integer): PCvvector_Size; cdecl;
Procedure   pCvVectorSizeDelete(const wrapper: PCvvector_Size); cdecl;
Function    pCvVectorSizeLength(const wrapper: PCvvector_Size): Integer; cdecl;
Function    pCvVectorSizeGet(const wrapper: PCvvector_Size; const index: Integer): PCvSize_t; cdecl;
Function    pCvVectorSizeSet(const wrapper: PCvvector_Size; const index: Integer; const val: PCvSize_t): PCvSize_t; cdecl;
Procedure   pCvVectorSizeToArray(const wrapper: PCvvector_Size; outvalues: PCvSizeS); cdecl;
Procedure   pCvVectorSizeFromArray(const wrapper: PCvvector_Size; inpvalues: PCvSizeS); cdecl;
Function    pCvVectorStringCreate(const n: Integer): PCvvector_String; cdecl;
Procedure   pCvVectorStringDelete(const wrapper: PCvvector_String); cdecl;
Function    pCvVectorStringLength(const wrapper: PCvvector_String): Integer; cdecl;
Function    pCvVectorStringGet(const wrapper: PCvvector_String; const index: Integer): PCvstring_t; cdecl;
Function    pCvVectorStringSet(const wrapper: PCvvector_String; const index: Integer; const val: PCvstring_t): PCvstring_t; cdecl;
Function    pCvVectordnn_TargetCreate(const n: Integer): PCvvector_Target; cdecl;
Procedure   pCvVectordnn_TargetDelete(const wrapper: PCvvector_Target); cdecl;
Function    pCvVectordnn_TargetLength(const wrapper: PCvvector_Target): Integer; cdecl;
Function    pCvVectordnn_TargetGet(const wrapper: PCvvector_Target; const index: Integer): PCvdnn_Target_t; cdecl;
Function    pCvVectordnn_TargetSet(const wrapper: PCvvector_Target; const index: Integer; const val: PCvdnn_Target_t): PCvdnn_Target_t; cdecl;
Function    pCvVectorUMatCreate(const n: Integer): PCvvector_UMat; cdecl;
Procedure   pCvVectorUMatDelete(const wrapper: PCvvector_UMat); cdecl;
Function    pCvVectorUMatLength(const wrapper: PCvvector_UMat): Integer; cdecl;
Function    pCvVectorUMatGet(const wrapper: PCvvector_UMat; const index: Integer): PCvUMat_t; cdecl;
Function    pCvVectorUMatSet(const wrapper: PCvvector_UMat; const index: Integer; const val: PCvUMat_t): PCvUMat_t; cdecl;
Function    pCvVectorVec4fCreate(const n: Integer): PCvvector_Vec4f; cdecl;
Procedure   pCvVectorVec4fDelete(const wrapper: PCvvector_Vec4f); cdecl;
Function    pCvVectorVec4fLength(const wrapper: PCvvector_Vec4f): Integer; cdecl;
Function    pCvVectorVec4fGet(const wrapper: PCvvector_Vec4f; const index: Integer): PCvVec4f_t; cdecl;
Function    pCvVectorVec4fSet(const wrapper: PCvvector_Vec4f; const index: Integer; const val: PCvVec4f_t): PCvVec4f_t; cdecl;
Procedure   pCvVectorVec4fToArray(const wrapper: PCvvector_Vec4f; outvalues: PCvVec4fS); cdecl;
Procedure   pCvVectorVec4fFromArray(const wrapper: PCvvector_Vec4f; inpvalues: PCvVec4fS); cdecl;
Function    pCvVectorVec6fCreate(const n: Integer): PCvvector_Vec6f; cdecl;
Procedure   pCvVectorVec6fDelete(const wrapper: PCvvector_Vec6f); cdecl;
Function    pCvVectorVec6fLength(const wrapper: PCvvector_Vec6f): Integer; cdecl;
Function    pCvVectorVec6fGet(const wrapper: PCvvector_Vec6f; const index: Integer): PCvVec6f_t; cdecl;
Function    pCvVectorVec6fSet(const wrapper: PCvvector_Vec6f; const index: Integer; const val: PCvVec6f_t): PCvVec6f_t; cdecl;
Procedure   pCvVectorVec6fToArray(const wrapper: PCvvector_Vec6f; outvalues: PCvVec6fS); cdecl;
Procedure   pCvVectorVec6fFromArray(const wrapper: PCvvector_Vec6f; inpvalues: PCvVec6fS); cdecl;
Function    pCvVectorcharCreate(const n: Integer): PCvvector_char; cdecl;
Procedure   pCvVectorcharDelete(const wrapper: PCvvector_char); cdecl;
Function    pCvVectorcharLength(const wrapper: PCvvector_char): Integer; cdecl;
Function    pCvVectorcharGet(const wrapper: PCvvector_char; const index: Integer): Char; cdecl;
Function    pCvVectorcharSet(const wrapper: PCvvector_char; const index: Integer; const val: Char): Char; cdecl;
Function    pCvVectordoubleCreate(const n: Integer): PCvvector_double; cdecl;
Procedure   pCvVectordoubleDelete(const wrapper: PCvvector_double); cdecl;
Function    pCvVectordoubleLength(const wrapper: PCvvector_double): Integer; cdecl;
Function    pCvVectordoubleGet(const wrapper: PCvvector_double; const index: Integer): Double; cdecl;
Function    pCvVectordoubleSet(const wrapper: PCvvector_double; const index: Integer; const val: Double): Double; cdecl;
Function    pCvVectorfloatCreate(const n: Integer): PCvvector_float; cdecl;
Procedure   pCvVectorfloatDelete(const wrapper: PCvvector_float); cdecl;
Function    pCvVectorfloatLength(const wrapper: PCvvector_float): Integer; cdecl;
Function    pCvVectorfloatGet(const wrapper: PCvvector_float; const index: Integer): Single; cdecl;
Function    pCvVectorfloatSet(const wrapper: PCvvector_float; const index: Integer; const val: Single): Single; cdecl;
Function    pCvVectorintCreate(const n: Integer): PCvvector_int; cdecl;
Procedure   pCvVectorintDelete(const wrapper: PCvvector_int); cdecl;
Function    pCvVectorintLength(const wrapper: PCvvector_int): Integer; cdecl;
Function    pCvVectorintGet(const wrapper: PCvvector_int; const index: Integer): Integer; cdecl;
Function    pCvVectorintSet(const wrapper: PCvvector_int; const index: Integer; const val: Integer): Integer; cdecl;
Function    pCvVector_stringCreate(const n: Integer): PCvvector__string; cdecl;
Procedure   pCvVector_stringDelete(const wrapper: PCvvector__string); cdecl;
Function    pCvVector_stringLength(const wrapper: PCvvector__string): Integer; cdecl;
Function    pCvVector_stringGet(const wrapper: PCvvector__string; const index: Integer): PCvstring_t; cdecl;
Function    pCvVector_stringSet(const wrapper: PCvvector__string; const index: Integer; const val: PCvstring_t): PCvstring_t; cdecl;
Function    pCvVectorucharCreate(const n: Integer): PCvvector_uchar; cdecl;
Procedure   pCvVectorucharDelete(const wrapper: PCvvector_uchar); cdecl;
Function    pCvVectorucharLength(const wrapper: PCvvector_uchar): Integer; cdecl;
Function    pCvVectorucharGet(const wrapper: PCvvector_uchar; const index: Integer): Byte; cdecl;
Function    pCvVectorucharSet(const wrapper: PCvvector_uchar; const index: Integer; const val: Byte): Byte; cdecl;
Function    pCvVectorvector_DMatchCreate(const n: Integer): PCvvector_vector_DMatch; cdecl;
Procedure   pCvVectorvector_DMatchDelete(const wrapper: PCvvector_vector_DMatch); cdecl;
Function    pCvVectorvector_DMatchLength(const wrapper: PCvvector_vector_DMatch): Integer; cdecl;
Function    pCvVectorvector_DMatchGet(const wrapper: PCvvector_vector_DMatch; const index: Integer): PCvvector_vector_DMatch; cdecl;
Function    pCvVectorvector_DMatchSet(const wrapper: PCvvector_vector_DMatch; const index: Integer; const val: PCvvector_vector_DMatch): PCvvector_vector_DMatch; cdecl;
Function    pCvVectorvector_KeyPointCreate(const n: Integer): PCvvector_vector_KeyPoint; cdecl;
Procedure   pCvVectorvector_KeyPointDelete(const wrapper: PCvvector_vector_KeyPoint); cdecl;
Function    pCvVectorvector_KeyPointLength(const wrapper: PCvvector_vector_KeyPoint): Integer; cdecl;
Function    pCvVectorvector_KeyPointGet(const wrapper: PCvvector_vector_KeyPoint; const index: Integer): PCvvector_vector_KeyPoint; cdecl;
Function    pCvVectorvector_KeyPointSet(const wrapper: PCvvector_vector_KeyPoint; const index: Integer; const val: PCvvector_vector_KeyPoint): PCvvector_vector_KeyPoint; cdecl;
Function    pCvVectorvector_MatCreate(const n: Integer): PCvvector_vector_Mat; cdecl;
Procedure   pCvVectorvector_MatDelete(const wrapper: PCvvector_vector_Mat); cdecl;
Function    pCvVectorvector_MatLength(const wrapper: PCvvector_vector_Mat): Integer; cdecl;
Function    pCvVectorvector_MatGet(const wrapper: PCvvector_vector_Mat; const index: Integer): PCvvector_vector_Mat; cdecl;
Function    pCvVectorvector_MatSet(const wrapper: PCvvector_vector_Mat; const index: Integer; const val: PCvvector_vector_Mat): PCvvector_vector_Mat; cdecl;
Function    pCvVectorvector_MatShapeCreate(const n: Integer): PCvvector_vector_MatShape; cdecl;
Procedure   pCvVectorvector_MatShapeDelete(const wrapper: PCvvector_vector_MatShape); cdecl;
Function    pCvVectorvector_MatShapeLength(const wrapper: PCvvector_vector_MatShape): Integer; cdecl;
Function    pCvVectorvector_MatShapeGet(const wrapper: PCvvector_vector_MatShape; const index: Integer): PCvvector_vector_MatShape; cdecl;
Function    pCvVectorvector_MatShapeSet(const wrapper: PCvvector_vector_MatShape; const index: Integer; const val: PCvvector_vector_MatShape): PCvvector_vector_MatShape; cdecl;
Function    pCvVectorvector_PointCreate(const n: Integer): PCvvector_vector_Point; cdecl;
Procedure   pCvVectorvector_PointDelete(const wrapper: PCvvector_vector_Point); cdecl;
Function    pCvVectorvector_PointLength(const wrapper: PCvvector_vector_Point): Integer; cdecl;
Function    pCvVectorvector_PointGet(const wrapper: PCvvector_vector_Point; const index: Integer): PCvvector_vector_Point; cdecl;
Function    pCvVectorvector_PointSet(const wrapper: PCvvector_vector_Point; const index: Integer; const val: PCvvector_vector_Point): PCvvector_vector_Point; cdecl;
Function    pCvVectorvector_Point2fCreate(const n: Integer): PCvvector_vector_Point2f; cdecl;
Procedure   pCvVectorvector_Point2fDelete(const wrapper: PCvvector_vector_Point2f); cdecl;
Function    pCvVectorvector_Point2fLength(const wrapper: PCvvector_vector_Point2f): Integer; cdecl;
Function    pCvVectorvector_Point2fGet(const wrapper: PCvvector_vector_Point2f; const index: Integer): PCvvector_vector_Point2f; cdecl;
Function    pCvVectorvector_Point2fSet(const wrapper: PCvvector_vector_Point2f; const index: Integer; const val: PCvvector_vector_Point2f): PCvvector_vector_Point2f; cdecl;
Function    pCvVectorvector_charCreate(const n: Integer): PCvvector_vector_char; cdecl;
Procedure   pCvVectorvector_charDelete(const wrapper: PCvvector_vector_char); cdecl;
Function    pCvVectorvector_charLength(const wrapper: PCvvector_vector_char): Integer; cdecl;
Function    pCvVectorvector_charGet(const wrapper: PCvvector_vector_char; const index: Integer): PCvvector_vector_char; cdecl;
Function    pCvVectorvector_charSet(const wrapper: PCvvector_vector_char; const index: Integer; const val: PCvvector_vector_char): PCvvector_vector_char; cdecl;
Function    pCvPtr_AKAZEConvert(const wrapper: PCvPtr_AKAZE): PCvAKAZE_t; cdecl;
Function    pCvPtr_AKAZECreate(const wrapper: PCvAKAZE_t): PCvPtr_AKAZE; cdecl;
Procedure   pCvPtr_AKAZEDelete(const cptr: PCvPtr_AKAZE;  const wrapper: PCvAKAZE_t); cdecl;
Function    pCvPtr_ANN_MLPConvert(const wrapper: PCvPtr_ANN_MLP): PCvml_ANN_MLP_t; cdecl;
Function    pCvPtr_ANN_MLPCreate(const wrapper: PCvml_ANN_MLP_t): PCvPtr_ANN_MLP; cdecl;
Procedure   pCvPtr_ANN_MLPDelete(const cptr: PCvPtr_ANN_MLP;  const wrapper: PCvml_ANN_MLP_t); cdecl;
Function    pCvPtr_AffineFeatureConvert(const wrapper: PCvPtr_AffineFeature): PCvAffineFeature_t; cdecl;
Function    pCvPtr_AffineFeatureCreate(const wrapper: PCvAffineFeature_t): PCvPtr_AffineFeature; cdecl;
Procedure   pCvPtr_AffineFeatureDelete(const cptr: PCvPtr_AffineFeature;  const wrapper: PCvAffineFeature_t); cdecl;
Function    pCvPtr_AgastFeatureDetectorConvert(const wrapper: PCvPtr_AgastFeatureDetector): PCvAgastFeatureDetector_t; cdecl;
Function    pCvPtr_AgastFeatureDetectorCreate(const wrapper: PCvAgastFeatureDetector_t): PCvPtr_AgastFeatureDetector; cdecl;
Procedure   pCvPtr_AgastFeatureDetectorDelete(const cptr: PCvPtr_AgastFeatureDetector;  const wrapper: PCvAgastFeatureDetector_t); cdecl;
Function    pCvPtr_AlignMTBConvert(const wrapper: PCvPtr_AlignMTB): PCvAlignMTB_t; cdecl;
Function    pCvPtr_AlignMTBCreate(const wrapper: PCvAlignMTB_t): PCvPtr_AlignMTB; cdecl;
Procedure   pCvPtr_AlignMTBDelete(const cptr: PCvPtr_AlignMTB;  const wrapper: PCvAlignMTB_t); cdecl;
Function    pCvPtr_BRISKConvert(const wrapper: PCvPtr_BRISK): PCvBRISK_t; cdecl;
Function    pCvPtr_BRISKCreate(const wrapper: PCvBRISK_t): PCvPtr_BRISK; cdecl;
Procedure   pCvPtr_BRISKDelete(const cptr: PCvPtr_BRISK;  const wrapper: PCvBRISK_t); cdecl;
Function    pCvPtr_BackgroundSubtractorKNNConvert(const wrapper: PCvPtr_BackgroundSubtractorKNN): PCvBackgroundSubtractorKNN_t; cdecl;
Function    pCvPtr_BackgroundSubtractorKNNCreate(const wrapper: PCvBackgroundSubtractorKNN_t): PCvPtr_BackgroundSubtractorKNN; cdecl;
Procedure   pCvPtr_BackgroundSubtractorKNNDelete(const cptr: PCvPtr_BackgroundSubtractorKNN;  const wrapper: PCvBackgroundSubtractorKNN_t); cdecl;
Function    pCvPtr_BackgroundSubtractorMOG2Convert(const wrapper: PCvPtr_BackgroundSubtractorMOG2): PCvBackgroundSubtractorMOG2_t; cdecl;
Function    pCvPtr_BackgroundSubtractorMOG2Create(const wrapper: PCvBackgroundSubtractorMOG2_t): PCvPtr_BackgroundSubtractorMOG2; cdecl;
Procedure   pCvPtr_BackgroundSubtractorMOG2Delete(const cptr: PCvPtr_BackgroundSubtractorMOG2;  const wrapper: PCvBackgroundSubtractorMOG2_t); cdecl;
Function    pCvPtr_BestOf2NearestMatcherConvert(const wrapper: PCvPtr_BestOf2NearestMatcher): PCvdetail_BestOf2NearestMatcher_t; cdecl;
Function    pCvPtr_BestOf2NearestMatcherCreate(const wrapper: PCvdetail_BestOf2NearestMatcher_t): PCvPtr_BestOf2NearestMatcher; cdecl;
Procedure   pCvPtr_BestOf2NearestMatcherDelete(const cptr: PCvPtr_BestOf2NearestMatcher;  const wrapper: PCvdetail_BestOf2NearestMatcher_t); cdecl;
Function    pCvPtr_BlenderConvert(const wrapper: PCvPtr_Blender): PCvdetail_Blender_t; cdecl;
Function    pCvPtr_BlenderCreate(const wrapper: PCvdetail_Blender_t): PCvPtr_Blender; cdecl;
Procedure   pCvPtr_BlenderDelete(const cptr: PCvPtr_Blender;  const wrapper: PCvdetail_Blender_t); cdecl;
Function    pCvPtr_CLAHEConvert(const wrapper: PCvPtr_CLAHE): PCvCLAHE_t; cdecl;
Function    pCvPtr_CLAHECreate(const wrapper: PCvCLAHE_t): PCvPtr_CLAHE; cdecl;
Procedure   pCvPtr_CLAHEDelete(const cptr: PCvPtr_CLAHE;  const wrapper: PCvCLAHE_t); cdecl;
Function    pCvPtr_CalibrateDebevecConvert(const wrapper: PCvPtr_CalibrateDebevec): PCvCalibrateDebevec_t; cdecl;
Function    pCvPtr_CalibrateDebevecCreate(const wrapper: PCvCalibrateDebevec_t): PCvPtr_CalibrateDebevec; cdecl;
Procedure   pCvPtr_CalibrateDebevecDelete(const cptr: PCvPtr_CalibrateDebevec;  const wrapper: PCvCalibrateDebevec_t); cdecl;
Function    pCvPtr_CalibrateRobertsonConvert(const wrapper: PCvPtr_CalibrateRobertson): PCvCalibrateRobertson_t; cdecl;
Function    pCvPtr_CalibrateRobertsonCreate(const wrapper: PCvCalibrateRobertson_t): PCvPtr_CalibrateRobertson; cdecl;
Procedure   pCvPtr_CalibrateRobertsonDelete(const cptr: PCvPtr_CalibrateRobertson;  const wrapper: PCvCalibrateRobertson_t); cdecl;
Function    pCvPtr_DISOpticalFlowConvert(const wrapper: PCvPtr_DISOpticalFlow): PCvDISOpticalFlow_t; cdecl;
Function    pCvPtr_DISOpticalFlowCreate(const wrapper: PCvDISOpticalFlow_t): PCvPtr_DISOpticalFlow; cdecl;
Procedure   pCvPtr_DISOpticalFlowDelete(const cptr: PCvPtr_DISOpticalFlow;  const wrapper: PCvDISOpticalFlow_t); cdecl;
Function    pCvPtr_DTreesConvert(const wrapper: PCvPtr_DTrees): PCvml_DTrees_t; cdecl;
Function    pCvPtr_DTreesCreate(const wrapper: PCvml_DTrees_t): PCvPtr_DTrees; cdecl;
Procedure   pCvPtr_DTreesDelete(const cptr: PCvPtr_DTrees;  const wrapper: PCvml_DTrees_t); cdecl;
Function    pCvPtr_DescriptorExtractorConvert(const wrapper: PCvPtr_DescriptorExtractor): PCvDescriptorExtractor_t; cdecl;
Function    pCvPtr_DescriptorExtractorCreate(const wrapper: PCvDescriptorExtractor_t): PCvPtr_DescriptorExtractor; cdecl;
Procedure   pCvPtr_DescriptorExtractorDelete(const cptr: PCvPtr_DescriptorExtractor;  const wrapper: PCvDescriptorExtractor_t); cdecl;
Function    pCvPtr_BFMatcherConvert(const wrapper: PCvPtr_BFMatcher): PCvBFMatcher_t; cdecl;
Function    pCvPtr_BFMatcherCreate(const wrapper: PCvBFMatcher_t): PCvPtr_BFMatcher; cdecl;
Procedure   pCvPtr_BFMatcherDelete(const cptr: PCvPtr_BFMatcher;  const wrapper: PCvBFMatcher_t); cdecl;
Function    pCvPtr_DescriptorMatcherConvert(const wrapper: PCvPtr_DescriptorMatcher): PCvDescriptorMatcher_t; cdecl;
Function    pCvPtr_DescriptorMatcherCreate(const wrapper: PCvDescriptorMatcher_t): PCvPtr_DescriptorMatcher; cdecl;
Procedure   pCvPtr_DescriptorMatcherDelete(const cptr: PCvPtr_DescriptorMatcher;  const wrapper: PCvDescriptorMatcher_t); cdecl;
Function    pCvPtr_FlannBasedMatcherConvert(const wrapper: PCvPtr_FlannBasedMatcher): PCvFlannBasedMatcher_t; cdecl;
Function    pCvPtr_FlannBasedMatcherCreate(const wrapper: PCvFlannBasedMatcher_t): PCvPtr_FlannBasedMatcher; cdecl;
Procedure   pCvPtr_FlannBasedMatcherDelete(const cptr: PCvPtr_FlannBasedMatcher;  const wrapper: PCvFlannBasedMatcher_t); cdecl;
Function    pCvPtr_EMConvert(const wrapper: PCvPtr_EM): PCvml_EM_t; cdecl;
Function    pCvPtr_EMCreate(const wrapper: PCvml_EM_t): PCvPtr_EM; cdecl;
Procedure   pCvPtr_EMDelete(const cptr: PCvPtr_EM;  const wrapper: PCvml_EM_t); cdecl;
Function    pCvPtr_ExposureCompensatorConvert(const wrapper: PCvPtr_ExposureCompensator): PCvdetail_ExposureCompensator_t; cdecl;
Function    pCvPtr_ExposureCompensatorCreate(const wrapper: PCvdetail_ExposureCompensator_t): PCvPtr_ExposureCompensator; cdecl;
Procedure   pCvPtr_ExposureCompensatorDelete(const cptr: PCvPtr_ExposureCompensator;  const wrapper: PCvdetail_ExposureCompensator_t); cdecl;
Function    pCvPtr_FaceDetectorYNConvert(const wrapper: PCvPtr_FaceDetectorYN): PCvFaceDetectorYN_t; cdecl;
Function    pCvPtr_FaceDetectorYNCreate(const wrapper: PCvFaceDetectorYN_t): PCvPtr_FaceDetectorYN; cdecl;
Procedure   pCvPtr_FaceDetectorYNDelete(const cptr: PCvPtr_FaceDetectorYN;  const wrapper: PCvFaceDetectorYN_t); cdecl;
Function    pCvPtr_RTreesConvert(const wrapper: PCvPtr_RTrees): PCvml_RTrees_t; cdecl;
Function    pCvPtr_RTreesCreate(const wrapper: PCvml_RTrees_t): PCvPtr_RTrees; cdecl;
Procedure   pCvPtr_RTreesDelete(const cptr: PCvPtr_RTrees;  const wrapper: PCvml_RTrees_t); cdecl;
Function    pCvPtr_BoostConvert(const wrapper: PCvPtr_Boost): PCvml_Boost_t; cdecl;
Function    pCvPtr_BoostCreate(const wrapper: PCvml_Boost_t): PCvPtr_Boost; cdecl;
Procedure   pCvPtr_BoostDelete(const cptr: PCvPtr_Boost;  const wrapper: PCvml_Boost_t); cdecl;
Function    pCvPtr_FaceRecognizerSFConvert(const wrapper: PCvPtr_FaceRecognizerSF): PCvFaceRecognizerSF_t; cdecl;
Function    pCvPtr_FaceRecognizerSFCreate(const wrapper: PCvFaceRecognizerSF_t): PCvPtr_FaceRecognizerSF; cdecl;
Procedure   pCvPtr_FaceRecognizerSFDelete(const cptr: PCvPtr_FaceRecognizerSF;  const wrapper: PCvFaceRecognizerSF_t); cdecl;
Function    pCvPtr_FarnebackOpticalFlowConvert(const wrapper: PCvPtr_FarnebackOpticalFlow): PCvFarnebackOpticalFlow_t; cdecl;
Function    pCvPtr_FarnebackOpticalFlowCreate(const wrapper: PCvFarnebackOpticalFlow_t): PCvPtr_FarnebackOpticalFlow; cdecl;
Procedure   pCvPtr_FarnebackOpticalFlowDelete(const cptr: PCvPtr_FarnebackOpticalFlow;  const wrapper: PCvFarnebackOpticalFlow_t); cdecl;
Function    pCvPtr_FastFeatureDetectorConvert(const wrapper: PCvPtr_FastFeatureDetector): PCvFastFeatureDetector_t; cdecl;
Function    pCvPtr_FastFeatureDetectorCreate(const wrapper: PCvFastFeatureDetector_t): PCvPtr_FastFeatureDetector; cdecl;
Procedure   pCvPtr_FastFeatureDetectorDelete(const cptr: PCvPtr_FastFeatureDetector;  const wrapper: PCvFastFeatureDetector_t); cdecl;
Function    pCvPtr_Feature2DConvert(const wrapper: PCvPtr_Feature2D): PCvFeature2D_t; cdecl;
Function    pCvPtr_Feature2DCreate(const wrapper: PCvFeature2D_t): PCvPtr_Feature2D; cdecl;
Procedure   pCvPtr_Feature2DDelete(const cptr: PCvPtr_Feature2D;  const wrapper: PCvFeature2D_t); cdecl;
Function    pCvPtr_FeatureDetectorConvert(const wrapper: PCvPtr_FeatureDetector): PCvFeatureDetector_t; cdecl;
Function    pCvPtr_FeatureDetectorCreate(const wrapper: PCvFeatureDetector_t): PCvPtr_FeatureDetector; cdecl;
Procedure   pCvPtr_FeatureDetectorDelete(const cptr: PCvPtr_FeatureDetector;  const wrapper: PCvFeatureDetector_t); cdecl;
Function    pCvPtr_FileStorageConvert(const wrapper: PCvPtr_FileStorage): PCvFileStorage_t; cdecl;
Function    pCvPtr_FileStorageCreate(const wrapper: PCvFileStorage_t): PCvPtr_FileStorage; cdecl;
Procedure   pCvPtr_FileStorageDelete(const cptr: PCvPtr_FileStorage;  const wrapper: PCvFileStorage_t); cdecl;
Function    pCvPtr_GFTTDetectorConvert(const wrapper: PCvPtr_GFTTDetector): PCvGFTTDetector_t; cdecl;
Function    pCvPtr_GFTTDetectorCreate(const wrapper: PCvGFTTDetector_t): PCvPtr_GFTTDetector; cdecl;
Procedure   pCvPtr_GFTTDetectorDelete(const cptr: PCvPtr_GFTTDetector;  const wrapper: PCvGFTTDetector_t); cdecl;
Function    pCvPtr_GeneralizedHoughBallardConvert(const wrapper: PCvPtr_GeneralizedHoughBallard): PCvGeneralizedHoughBallard_t; cdecl;
Function    pCvPtr_GeneralizedHoughBallardCreate(const wrapper: PCvGeneralizedHoughBallard_t): PCvPtr_GeneralizedHoughBallard; cdecl;
Procedure   pCvPtr_GeneralizedHoughBallardDelete(const cptr: PCvPtr_GeneralizedHoughBallard;  const wrapper: PCvGeneralizedHoughBallard_t); cdecl;
Function    pCvPtr_GeneralizedHoughGuilConvert(const wrapper: PCvPtr_GeneralizedHoughGuil): PCvGeneralizedHoughGuil_t; cdecl;
Function    pCvPtr_GeneralizedHoughGuilCreate(const wrapper: PCvGeneralizedHoughGuil_t): PCvPtr_GeneralizedHoughGuil; cdecl;
Procedure   pCvPtr_GeneralizedHoughGuilDelete(const cptr: PCvPtr_GeneralizedHoughGuil;  const wrapper: PCvGeneralizedHoughGuil_t); cdecl;
Function    pCvPtr_KAZEConvert(const wrapper: PCvPtr_KAZE): PCvKAZE_t; cdecl;
Function    pCvPtr_KAZECreate(const wrapper: PCvKAZE_t): PCvPtr_KAZE; cdecl;
Procedure   pCvPtr_KAZEDelete(const cptr: PCvPtr_KAZE;  const wrapper: PCvKAZE_t); cdecl;
Function    pCvPtr_KNearestConvert(const wrapper: PCvPtr_KNearest): PCvml_KNearest_t; cdecl;
Function    pCvPtr_KNearestCreate(const wrapper: PCvml_KNearest_t): PCvPtr_KNearest; cdecl;
Procedure   pCvPtr_KNearestDelete(const cptr: PCvPtr_KNearest;  const wrapper: PCvml_KNearest_t); cdecl;
Function    pCvPtr_LayerConvert(const wrapper: PCvPtr_Layer): PCvdnn_Layer_t; cdecl;
Function    pCvPtr_LayerCreate(const wrapper: PCvdnn_Layer_t): PCvPtr_Layer; cdecl;
Procedure   pCvPtr_LayerDelete(const cptr: PCvPtr_Layer;  const wrapper: PCvdnn_Layer_t); cdecl;
Function    pCvPtr_LineSegmentDetectorConvert(const wrapper: PCvPtr_LineSegmentDetector): PCvLineSegmentDetector_t; cdecl;
Function    pCvPtr_LineSegmentDetectorCreate(const wrapper: PCvLineSegmentDetector_t): PCvPtr_LineSegmentDetector; cdecl;
Procedure   pCvPtr_LineSegmentDetectorDelete(const cptr: PCvPtr_LineSegmentDetector;  const wrapper: PCvLineSegmentDetector_t); cdecl;
Function    pCvPtr_LogisticRegressionConvert(const wrapper: PCvPtr_LogisticRegression): PCvml_LogisticRegression_t; cdecl;
Function    pCvPtr_LogisticRegressionCreate(const wrapper: PCvml_LogisticRegression_t): PCvPtr_LogisticRegression; cdecl;
Procedure   pCvPtr_LogisticRegressionDelete(const cptr: PCvPtr_LogisticRegression;  const wrapper: PCvml_LogisticRegression_t); cdecl;
Function    pCvPtr_MSERConvert(const wrapper: PCvPtr_MSER): PCvMSER_t; cdecl;
Function    pCvPtr_MSERCreate(const wrapper: PCvMSER_t): PCvPtr_MSER; cdecl;
Procedure   pCvPtr_MSERDelete(const cptr: PCvPtr_MSER;  const wrapper: PCvMSER_t); cdecl;
Function    pCvPtr_MergeDebevecConvert(const wrapper: PCvPtr_MergeDebevec): PCvMergeDebevec_t; cdecl;
Function    pCvPtr_MergeDebevecCreate(const wrapper: PCvMergeDebevec_t): PCvPtr_MergeDebevec; cdecl;
Procedure   pCvPtr_MergeDebevecDelete(const cptr: PCvPtr_MergeDebevec;  const wrapper: PCvMergeDebevec_t); cdecl;
Function    pCvPtr_MergeMertensConvert(const wrapper: PCvPtr_MergeMertens): PCvMergeMertens_t; cdecl;
Function    pCvPtr_MergeMertensCreate(const wrapper: PCvMergeMertens_t): PCvPtr_MergeMertens; cdecl;
Procedure   pCvPtr_MergeMertensDelete(const cptr: PCvPtr_MergeMertens;  const wrapper: PCvMergeMertens_t); cdecl;
Function    pCvPtr_MergeRobertsonConvert(const wrapper: PCvPtr_MergeRobertson): PCvMergeRobertson_t; cdecl;
Function    pCvPtr_MergeRobertsonCreate(const wrapper: PCvMergeRobertson_t): PCvPtr_MergeRobertson; cdecl;
Procedure   pCvPtr_MergeRobertsonDelete(const cptr: PCvPtr_MergeRobertson;  const wrapper: PCvMergeRobertson_t); cdecl;
Function    pCvPtr_NormalBayesClassifierConvert(const wrapper: PCvPtr_NormalBayesClassifier): PCvml_NormalBayesClassifier_t; cdecl;
Function    pCvPtr_NormalBayesClassifierCreate(const wrapper: PCvml_NormalBayesClassifier_t): PCvPtr_NormalBayesClassifier; cdecl;
Procedure   pCvPtr_NormalBayesClassifierDelete(const cptr: PCvPtr_NormalBayesClassifier;  const wrapper: PCvml_NormalBayesClassifier_t); cdecl;
Function    pCvPtr_ORBConvert(const wrapper: PCvPtr_ORB): PCvORB_t; cdecl;
Function    pCvPtr_ORBCreate(const wrapper: PCvORB_t): PCvPtr_ORB; cdecl;
Procedure   pCvPtr_ORBDelete(const cptr: PCvPtr_ORB;  const wrapper: PCvORB_t); cdecl;
Function    pCvPtr_OriginalClassNameConvert(const wrapper: PCvPtr_OriginalClassName): PCvutils_nested_OriginalClassName_t; cdecl;
Function    pCvPtr_OriginalClassNameCreate(const wrapper: PCvutils_nested_OriginalClassName_t): PCvPtr_OriginalClassName; cdecl;
Procedure   pCvPtr_OriginalClassNameDelete(const cptr: PCvPtr_OriginalClassName;  const wrapper: PCvutils_nested_OriginalClassName_t); cdecl;
Function    pCvPtr_ParamGridConvert(const wrapper: PCvPtr_ParamGrid): PCvml_ParamGrid_t; cdecl;
Function    pCvPtr_ParamGridCreate(const wrapper: PCvml_ParamGrid_t): PCvPtr_ParamGrid; cdecl;
Procedure   pCvPtr_ParamGridDelete(const cptr: PCvPtr_ParamGrid;  const wrapper: PCvml_ParamGrid_t); cdecl;
Function    pCvPtr_QRCodeEncoderConvert(const wrapper: PCvPtr_QRCodeEncoder): PCvQRCodeEncoder_t; cdecl;
Function    pCvPtr_QRCodeEncoderCreate(const wrapper: PCvQRCodeEncoder_t): PCvPtr_QRCodeEncoder; cdecl;
Procedure   pCvPtr_QRCodeEncoderDelete(const cptr: PCvPtr_QRCodeEncoder;  const wrapper: PCvQRCodeEncoder_t); cdecl;
Function    pCvPtr_SIFTConvert(const wrapper: PCvPtr_SIFT): PCvSIFT_t; cdecl;
Function    pCvPtr_SIFTCreate(const wrapper: PCvSIFT_t): PCvPtr_SIFT; cdecl;
Procedure   pCvPtr_SIFTDelete(const cptr: PCvPtr_SIFT;  const wrapper: PCvSIFT_t); cdecl;
Function    pCvPtr_SVMConvert(const wrapper: PCvPtr_SVM): PCvml_SVM_t; cdecl;
Function    pCvPtr_SVMCreate(const wrapper: PCvml_SVM_t): PCvPtr_SVM; cdecl;
Procedure   pCvPtr_SVMDelete(const cptr: PCvPtr_SVM;  const wrapper: PCvml_SVM_t); cdecl;
Function    pCvPtr_SVMSGDConvert(const wrapper: PCvPtr_SVMSGD): PCvml_SVMSGD_t; cdecl;
Function    pCvPtr_SVMSGDCreate(const wrapper: PCvml_SVMSGD_t): PCvPtr_SVMSGD; cdecl;
Procedure   pCvPtr_SVMSGDDelete(const cptr: PCvPtr_SVMSGD;  const wrapper: PCvml_SVMSGD_t); cdecl;
Function    pCvPtr_SeamFinderConvert(const wrapper: PCvPtr_SeamFinder): PCvdetail_SeamFinder_t; cdecl;
Function    pCvPtr_SeamFinderCreate(const wrapper: PCvdetail_SeamFinder_t): PCvPtr_SeamFinder; cdecl;
Procedure   pCvPtr_SeamFinderDelete(const cptr: PCvPtr_SeamFinder;  const wrapper: PCvdetail_SeamFinder_t); cdecl;
Function    pCvPtr_SimpleBlobDetectorConvert(const wrapper: PCvPtr_SimpleBlobDetector): PCvSimpleBlobDetector_t; cdecl;
Function    pCvPtr_SimpleBlobDetectorCreate(const wrapper: PCvSimpleBlobDetector_t): PCvPtr_SimpleBlobDetector; cdecl;
Procedure   pCvPtr_SimpleBlobDetectorDelete(const cptr: PCvPtr_SimpleBlobDetector;  const wrapper: PCvSimpleBlobDetector_t); cdecl;
Function    pCvPtr_SparsePyrLKOpticalFlowConvert(const wrapper: PCvPtr_SparsePyrLKOpticalFlow): PCvSparsePyrLKOpticalFlow_t; cdecl;
Function    pCvPtr_SparsePyrLKOpticalFlowCreate(const wrapper: PCvSparsePyrLKOpticalFlow_t): PCvPtr_SparsePyrLKOpticalFlow; cdecl;
Procedure   pCvPtr_SparsePyrLKOpticalFlowDelete(const cptr: PCvPtr_SparsePyrLKOpticalFlow;  const wrapper: PCvSparsePyrLKOpticalFlow_t); cdecl;
Function    pCvPtr_StereoBMConvert(const wrapper: PCvPtr_StereoBM): PCvStereoBM_t; cdecl;
Function    pCvPtr_StereoBMCreate(const wrapper: PCvStereoBM_t): PCvPtr_StereoBM; cdecl;
Procedure   pCvPtr_StereoBMDelete(const cptr: PCvPtr_StereoBM;  const wrapper: PCvStereoBM_t); cdecl;
Function    pCvPtr_StereoSGBMConvert(const wrapper: PCvPtr_StereoSGBM): PCvStereoSGBM_t; cdecl;
Function    pCvPtr_StereoSGBMCreate(const wrapper: PCvStereoSGBM_t): PCvPtr_StereoSGBM; cdecl;
Procedure   pCvPtr_StereoSGBMDelete(const cptr: PCvPtr_StereoSGBM;  const wrapper: PCvStereoSGBM_t); cdecl;
Function    pCvPtr_StitcherConvert(const wrapper: PCvPtr_Stitcher): PCvStitcher_t; cdecl;
Function    pCvPtr_StitcherCreate(const wrapper: PCvStitcher_t): PCvPtr_Stitcher; cdecl;
Procedure   pCvPtr_StitcherDelete(const cptr: PCvPtr_Stitcher;  const wrapper: PCvStitcher_t); cdecl;
Function    pCvPtr_TimelapserConvert(const wrapper: PCvPtr_Timelapser): PCvdetail_Timelapser_t; cdecl;
Function    pCvPtr_TimelapserCreate(const wrapper: PCvdetail_Timelapser_t): PCvPtr_Timelapser; cdecl;
Procedure   pCvPtr_TimelapserDelete(const cptr: PCvPtr_Timelapser;  const wrapper: PCvdetail_Timelapser_t); cdecl;
Function    pCvPtr_TonemapConvert(const wrapper: PCvPtr_Tonemap): PCvTonemap_t; cdecl;
Function    pCvPtr_TonemapCreate(const wrapper: PCvTonemap_t): PCvPtr_Tonemap; cdecl;
Procedure   pCvPtr_TonemapDelete(const cptr: PCvPtr_Tonemap;  const wrapper: PCvTonemap_t); cdecl;
Function    pCvPtr_TonemapDragoConvert(const wrapper: PCvPtr_TonemapDrago): PCvTonemapDrago_t; cdecl;
Function    pCvPtr_TonemapDragoCreate(const wrapper: PCvTonemapDrago_t): PCvPtr_TonemapDrago; cdecl;
Procedure   pCvPtr_TonemapDragoDelete(const cptr: PCvPtr_TonemapDrago;  const wrapper: PCvTonemapDrago_t); cdecl;
Function    pCvPtr_TonemapMantiukConvert(const wrapper: PCvPtr_TonemapMantiuk): PCvTonemapMantiuk_t; cdecl;
Function    pCvPtr_TonemapMantiukCreate(const wrapper: PCvTonemapMantiuk_t): PCvPtr_TonemapMantiuk; cdecl;
Procedure   pCvPtr_TonemapMantiukDelete(const cptr: PCvPtr_TonemapMantiuk;  const wrapper: PCvTonemapMantiuk_t); cdecl;
Function    pCvPtr_TonemapReinhardConvert(const wrapper: PCvPtr_TonemapReinhard): PCvTonemapReinhard_t; cdecl;
Function    pCvPtr_TonemapReinhardCreate(const wrapper: PCvTonemapReinhard_t): PCvPtr_TonemapReinhard; cdecl;
Procedure   pCvPtr_TonemapReinhardDelete(const cptr: PCvPtr_TonemapReinhard;  const wrapper: PCvTonemapReinhard_t); cdecl;
Function    pCvPtr_TrackerDaSiamRPNConvert(const wrapper: PCvPtr_TrackerDaSiamRPN): PCvTrackerDaSiamRPN_t; cdecl;
Function    pCvPtr_TrackerDaSiamRPNCreate(const wrapper: PCvTrackerDaSiamRPN_t): PCvPtr_TrackerDaSiamRPN; cdecl;
Procedure   pCvPtr_TrackerDaSiamRPNDelete(const cptr: PCvPtr_TrackerDaSiamRPN;  const wrapper: PCvTrackerDaSiamRPN_t); cdecl;
Function    pCvPtr_TrackerGOTURNConvert(const wrapper: PCvPtr_TrackerGOTURN): PCvTrackerGOTURN_t; cdecl;
Function    pCvPtr_TrackerGOTURNCreate(const wrapper: PCvTrackerGOTURN_t): PCvPtr_TrackerGOTURN; cdecl;
Procedure   pCvPtr_TrackerGOTURNDelete(const cptr: PCvPtr_TrackerGOTURN;  const wrapper: PCvTrackerGOTURN_t); cdecl;
Function    pCvPtr_TrackerMILConvert(const wrapper: PCvPtr_TrackerMIL): PCvTrackerMIL_t; cdecl;
Function    pCvPtr_TrackerMILCreate(const wrapper: PCvTrackerMIL_t): PCvPtr_TrackerMIL; cdecl;
Procedure   pCvPtr_TrackerMILDelete(const cptr: PCvPtr_TrackerMIL;  const wrapper: PCvTrackerMIL_t); cdecl;
Function    pCvPtr_TrainDataConvert(const wrapper: PCvPtr_TrainData): PCvml_TrainData_t; cdecl;
Function    pCvPtr_TrainDataCreate(const wrapper: PCvml_TrainData_t): PCvPtr_TrainData; cdecl;
Procedure   pCvPtr_TrainDataDelete(const cptr: PCvPtr_TrainData;  const wrapper: PCvml_TrainData_t); cdecl;
Function    pCvPtr_VariationalRefinementConvert(const wrapper: PCvPtr_VariationalRefinement): PCvVariationalRefinement_t; cdecl;
Function    pCvPtr_VariationalRefinementCreate(const wrapper: PCvVariationalRefinement_t): PCvPtr_VariationalRefinement; cdecl;
Procedure   pCvPtr_VariationalRefinementDelete(const cptr: PCvPtr_VariationalRefinement;  const wrapper: PCvVariationalRefinement_t); cdecl;
Function    pCvPtr_flann_IndexParamsConvert(const wrapper: PCvPtr_flann_IndexParams): PCvIndexParams_t; cdecl;
Function    pCvPtr_flann_IndexParamsCreate(const wrapper: PCvIndexParams_t): PCvPtr_flann_IndexParams; cdecl;
Procedure   pCvPtr_flann_IndexParamsDelete(const cptr: PCvPtr_flann_IndexParams;  const wrapper: PCvIndexParams_t); cdecl;
Function    pCvPtr_flann_SearchParamsConvert(const wrapper: PCvPtr_flann_SearchParams): PCvSearchParams_t; cdecl;
Function    pCvPtr_flann_SearchParamsCreate(const wrapper: PCvSearchParams_t): PCvPtr_flann_SearchParams; cdecl;
Procedure   pCvPtr_flann_SearchParamsDelete(const cptr: PCvPtr_flann_SearchParams;  const wrapper: PCvSearchParams_t); cdecl;
Function    pCvPtr_floatConvert(const wrapper: PCvPtr_float): Single; cdecl;
Function    pCvPtr_floatCreate(): PCvPtr_float; cdecl;
Procedure   pCvPtr_floatDelete(const cptr: PCvPtr_float); cdecl;
